### ISSUE TITLE
iPad Landscape 90 degrees rotated

### ISSUE THREAD

**Issue by derdida** [hyperoslo/ImagePicker#100]
Hello,
thanks for sharing this great plugin! Ill got a problem when ill try it with my iPad in Landscape Mode - the CameraView is always rotated by 90 degrees.

Is this a generally bug from iOS? Or a bug from your Plugin?

Thanks in advance.

**Comment by zenangst** [comment]
@derdida oh hai!
To be totally honest with you, we haven't really tested this on an iPad that well so this might just be that `ImagePicker` is not optimised for iPad. We will have a look and see what we can come up with.

Thanks for reporting this issue to us and supporting `ImagePicker`!

And yeah, sorry for not getting back to you sooner, it's been crazy days at the office lately. Poor excuse that you know, life :sunglasses:

**Comment by derdida** [comment]
Thanks for your reply. Would be great if you can check it on iPad - there are still some issues on Portrait mode too (the menu is in the middle of the screen).

Thanks again for sharing!

**Comment by BenchR267** [comment]
Maybe this fixes the problem? https://github.com/hyperoslo/ImagePicker/pull/104

**Comment by zenangst** [comment]
@derdida could you try `master` now to see if that works?

**Comment by aashishdhawan** [comment]
@zenangst I think this is not happening on `master`. Wanna test and close this?

**Comment by zenangst** [comment]
@derdida closing this now, feel free to open it again if it is still an issue in `1.3.0` 😁

**Comment by nishantanthwal** [comment]
I am still facing this issue in my iPad app. Unable to use it because of this issue..
#SwiftBridge
