### ISSUE TITLE
Metadata support

### ISSUE THREAD

**Issue by fnakstad** [hyperoslo/ImagePicker#102]
Hey guys! Great job on this library. My favorite image picker by far, and currently attempting to use it in my own app project.
 
One problem I'm having is that I also need to extract EXIF data for each image, so that I can store geotags and timestamps along with the raw image. As far as I can tell, this is not supported yet, and I'm guessing it will have to be done independently via the Photos Framework. Am I missing an obvious feature here? Or are there perhaps plans to also include metadata in the ImagePickerDelegate callbacks?

**Comment by zenangst** [comment]
Hey @fnakstad, right now we don't support any type of meta data because it hasn't been a requirement for us but it would be super cool if it did! Feel free to make a PR to add this kind of functionality, regardless if you do or don't, we will keep it in our backlog so that it doesn't get lost (personally I would love this feature).

Thanks for supporting `ImagePicker` and bringing this to our attention!

**Comment by fnakstad** [comment]
Cool! I checked into it some more, and discovered that this can be done fairly easily for photos taken with the standard camera app by directly accessing the assets, for example like this:
```swift
func doneButtonDidPress(images: [UIImage]) {
    imagePicker.dismissViewControllerAnimated(true, completion: nil)
    for imageAsset in imagePicker.stack.assets {
        let options = PHContentEditingInputRequestOptions()
        options.networkAccessAllowed = true
        imageAsset.requestContentEditingInputWithOptions(options) { (contentEditingInput: PHContentEditingInput?, _) -> Void in
            let fullImage = CIImage(contentsOfURL: contentEditingInput!.fullSizeImageURL!)
            print(fullImage?.properties)
        }
    }
}
```

The `fullImage?.properties` is a dictionary containing various metadata such as GPS, EXIF, TIFF, etc. This works perfectly when using a picture taken with the standard camera app and loaded with ImagePicker. However, when snapping a picture with the custom CameraView of ImagePicker a lot of this data isn't stored along with the picture, so the dictionary is missing EXIF and GPS data. For this kind of use-case it might be preferable if the imageAssets themselves were passed as arguments to the doneButtonDidPress callback, but at least this works for now.

As far as I can tell The EXIF data can be fetched from the dictionary returned by `AVCaptureStillImageOutput.jpegStillImageNSDataRepresentation`, but the GPS location needs to be manually fetched begging a dependency on CoreLocation. I might scrap together an initial PR after some more experimentation.
