### ISSUE TITLE
I am trying to use the demo with latest cocoda pod and xcode 7 but its not working

### ISSUE THREAD

**Issue by inafsdeveloper** [hyperoslo/ImagePicker#108]
I am a newbie at swift programming. I am getting same error ImagePicker No such module found.

**Comment by inafsdeveloper** [comment]
I figured it out... consider the issue close

**Comment by zenangst** [comment]
@inafsdeveloper awesome that you solved it, what was it?

**Comment by dheerajbhaskar** [comment]
@inafsdeveloper same error, what worked for you?
