### ISSUE TITLE
UI troubles with ImagePicker in a tabBarController

### ISSUE THREAD

**Issue by baqtiste** [hyperoslo/ImagePicker#110]
Hi,

It's seems that image gallery constraints are not set correctly when ImagePicker is embed in an tabbar controller or any navigation controller (I try to make it work with [EZSwipeController](https://github.com/goktugyil/EZSwipeController))

![img_3934 1](https://cloud.githubusercontent.com/assets/4132014/13050021/fd785290-d3f0-11e5-8163-acf918217f78.jpg)
![img_3936](https://cloud.githubusercontent.com/assets/4132014/13050022/fd9fa412-d3f0-11e5-9c86-f56992cde467.jpg)

Do you have any fix ?
thanks

**Comment by RamonGilabert** [comment]
Hey @baqtiste, is this still a thing? If so feel free to reopen! :)
