### ISSUE TITLE
Take a picture programmatically

### ISSUE THREAD

**Issue by iroller** [hyperoslo/ImagePicker#111]
Hi. I have a use case where I embed the whole `ImagePickerController()` into a small subview on the screen. I'm trying to remove all the buttons from the subview and call take-picture from parent controller.

The following gives me almost what I need - it triggers `cancelButtonDidPress()` in parent viewController since no picture was triggered:
```
imagePickerController.bottomContainer.doneButton.sendActionsForControlEvents(UIControlEvents.TouchUpInside)
```

Is there any way to make it take a picture programmatically and trigger `doneButtonDidPress([UIImage])`?

Thanks for the project btw, it's great.

**Comment by aashishdhawan** [comment]
Thanks @iroller.

`Hi. I have a use case where I embed the whole ImagePickerController() into a small subview on the screen. I'm trying to remove all the buttons from the subview and call take-picture from parent controller.
`

I do not think `ImagePicker` is the right choice for what you are trying to do as main purpose of `ImagePicker` is different. 

@zenangst
