### ISSUE TITLE
Only Photo Library

### ISSUE THREAD

**Issue by vinbhai4u** [hyperoslo/ImagePicker#113]
Can we have an option to select only images from gallery/Photo Library, with multi select? 
Just disable the camera maybe?

**Comment by aashishdhawan** [comment]
Well...only selecting images from gallery is not the purpose of ImagePicker. Camera is one major part of this. There are other libraries available which only select (multi select) images from gallery without showing the camera. 

@zenangst Should we close this?

**Comment by zenangst** [comment]
@vinbhai4u I agree with @aashishdhawan here. 
I'm all for customisation when it makes sense, however, I would suggest using a different library that fits your needs for just selecting images. I'm gonna go ahead and close this one.

**Comment by RamonGilabert** [comment]
Although in @vinbhai4u defense, we have plans to allow inside the ImagePicker to open just a library of images, even though that's going to be with the camera still there, so it will support both but with the full library instead of one row of images.

**Comment by vinbhai4u** [comment]
@RamonGilabert thanks, that feature will be great. we could swipe the image gallery slider upward and make the whole screen with gallery images.

**Comment by choujar** [comment]
Hi, did this ever happen?

**Comment by boboxiaodd** [comment]
choose a photo now popup three Privacy confirm, i need an option to disable video. @aashishdhawan
