### ISSUE TITLE
UI in landscape looks weird

### ISSUE THREAD

**Issue by vronin** [hyperoslo/ImagePicker#115]
Gallery occupy a lot of space and as result, the preview window become really squeezed.

I think the best way to handle it the same way as Camera application handles it. The layout should not change, just couple of controls should be rotated (flash, rear camera, pictures of gallery and stack).

**Comment by aashishdhawan** [comment]
@vronin Agreed. Specially in landscape mode situation becomes worse. Thanks for suggestion. We'll look at this in future release meanwhile we'll keep you posted.

**Comment by diogoAntunes** [comment]
What do you guys think of moving the UIViews to a .xib and auto layout? That way we can pretty much clear all the manually creation of constraints and apply adaptive layout 👍

**Comment by vronin** [comment]
@diogoAntunes +1

**Comment by vickeryj** [comment]
It's not a xib, but if anyone is hungry for the requested behavior here's my PR that builds it in code: https://github.com/hyperoslo/ImagePicker/pull/182

**Comment by RamonGilabert** [comment]
Closing for #186.
