### ISSUE TITLE
iPad 2 crash

### ISSUE THREAD

**Issue by damien-nd** [hyperoslo/ImagePicker#124]
Hello.

I start to look on the code but still not found where it is.

On iPad 2, I get a crash with this log:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Can't add <AVCaptureDeviceInput: 0x18e53330 [Caméra arrière]> because the device does not support AVCaptureSessionPreset1920x1080.  Use -[AVCaptureDevice supportsAVCaptureSessionPreset:].'
```

I don't know why part of the error is french, but 'Caméra arrière' means 'Rear camera'.
I do check with code `for d in AVCaptureDevice.devices()` and rear and front camera don't support `AVCaptureSessionPreset1920x1080`

Is this settings can be change or it is fixed on your code?

Thank you.

**Comment by zenangst** [comment]
@damien-nd could you test this towards `master` and confirm or deny that this is fixed? Thanks for bringing this to our attention!

**Comment by damien-nd** [comment]
@zenangst Sorry for the delay. I try it today and it fix the bug. Just one thing, with carthage, you should use tag more often, because you can not just be on master branch (or at least I do not known how to).
But everything perfect for me, thank you.
