### ISSUE TITLE
Dangerous warning 

### ISSUE THREAD

**Issue by aashishdhawan** [hyperoslo/ImagePicker#126]
getting following warning in console...I am not sure about steps to reproduce...will debug when bandwidth is available. 
`2016-04-01 05:54:46.928 ImagePickerDemo[1746:533854] This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.
`

**Comment by guidove** [comment]
Hi. Got the same warning. And also got a BS Mach Error just before this warning. In ImagePickerController.swift I wrapped everything inside  viewDidLoad, viewWillAppear, viewDidAppear, pickerButtonDidPress, doneButtonDidPress, cancelButtonDidPress, imageStackViewDidPress into dispatch_async(dispatch_get_main_queue()) { ... } That seemed to get rid of the above warning. BS Mach Error still appears though somehow. 

I know this is more like a "wide spectrum" solution, but unfortunately don't have time to go into the details at the moment. Thought this might be helpful in figuring out the exact cause though.

**Comment by onmyway133** [comment]
@aashishdhawan @guidove thanks for letting us know. I'm using https://github.com/onmyway133/MainThreadGuard to check it

**Comment by vinbhai4u** [comment]
Same warning in iPad and iPhone 5, 
Also after taking a picture from camera, then the gallery selection gets stuck

**Comment by aashishdhawan** [comment]
@vinbhai4u @guidove This has been fixed in #136
