### ISSUE TITLE
Wrong height issue

### ISSUE THREAD

**Issue by kosicki123** [hyperoslo/ImagePicker#135]
If I slide up the image gallery, take a photo (wait until it minimizes), slide it up again, do the middle and then to the maximum slide up, photos get wrong height. Anyone knows a solution for this issue?
![photo242196152625245088](https://cloud.githubusercontent.com/assets/1424811/14320790/bf2f41fa-fbec-11e5-9a16-f783752f33cf.jpg)

**Comment by aashishdhawan** [comment]
@kosicki123 Please try latest version 1.3.
Closing this issue. Feel free to reopen in case issue persists.

**Comment by kosicki123** [comment]
I'm using latest version 1.3.. :/

**Comment by aashishdhawan** [comment]
@kosicki123 reopening this. Let me check this again.

**Comment by onmyway133** [comment]
This may have been solved by newer versions of `ImagePicker` because of some refactorings. You can try `2.1.1`. Closing this for now, but feel free to reopen it if you have any issues
