### ISSUE TITLE
Swift 3.0 Warnings

### ISSUE THREAD

**Issue by mehfuzh** [hyperoslo/ImagePicker#138]
After updating to the latest Xcode, I am getting the following warnings:

BottomView/BottomContainerView.swift:35:36: Use of string literal for Objective-C selectors is deprecated; use '#selector' instead
BottomView/BottomContainerView.swift:54:37: Use of string literal for Objective-C selectors is deprecated; use '#selector' instead
ImageGalleryView.swift:64:37: Use of string literal for Objective-C selectors is deprecated; use '#selector' instead

Similar warnings:

TopView.swift
BottomPicker.swift
StackView.swift

**Comment by aashishdhawan** [comment]
@mehfuzh This issue has been resolved.

**Comment by mehfuzh** [comment]
@aashishdhawan Thanks!

However, I think that the pod is not yet updated.
