### ISSUE TITLE
Hold for Video, Tap for photo

### ISSUE THREAD

**Issue by MartinQue** [hyperoslo/ImagePicker#147]
Can i incorporate this: ie: hold for video, tap for photo just like whatsapp into the imagePicker? and if so, how?

Thanks in advance

**Comment by RamonGilabert** [comment]
We are not yet supporting videos in ImagePicker, but we are planning to, and this is the way I was thinking to implement it. We'll keep you posted here, @MartinQue.

**Comment by vronin** [comment]
+1

**Comment by ebalassanian** [comment]
+1

**Comment by RobertNNms** [comment]
+1

**Comment by jjjeeerrr111** [comment]
Is this still in the works?

**Comment by oalvarez** [comment]
Any news about this?

**Comment by Pulichev** [comment]
+1

**Comment by zenangst** [comment]
If anyone is up for making this into a PR, we would gladly review it 😎

**Comment by hcrgithub** [comment]
+1
