### ISSUE TITLE
Conflict between ImagePickerController and ImagePickerDelegate methods

### ISSUE THREAD

**Issue by aliasbody** [hyperoslo/ImagePicker#154]
Hello,

Maybe I am the "dumb" programmer, and if so please forgive me, but I'll ask the question anyway.

I need to implement a UIViewController inside a UINavigationController with a UITabBarController. For this I created the class like this:

```
class VC_MyView: ImagePickerController, ImagePickerDelegate {
    override func viewDidLoad() {
        self.viewDidLoad() // Necessary otherwise the ImagePickerView won't start
        self.delegate = self
    }
}
```

Not the delegate protocol makes me add the usual 3 functions:
`func wrapperDidPress(images: [UIImage])`
`func doneButtonDidPress(images: [UIImage])`
`func cancelButtonDidPress()`

The problem is with **cancelButtonDidPress()** since it conflicts with a function with the same name under ImagePickerController.

The only soluton I've found was to replace all the functions from **BottomContainerView.swift** by adding a "bottom" before every function name (and then correct the code at the right classes), which will make it look like this:

```
protocol BottomContainerViewDelegate: class {
    func bottomPickerButtonDidPress()
    func bottomDoneButtonDidPress()
    func bottomCancelButtonDidPress()
    func bottomImageStackViewDidPress()
}
```

This is far from perfect, but I really don't know how to solve the problem otherwise, and this is why I'm creating this issue.

So is this a real problem, or is it simply a skill (or lack of it) problem?

**Comment by erickva** [comment]
Hey aliasbody, we are all learning! :D

Perhaps you should declare your Class like this:

```
...
import ImagePicker 
...
class VC_MyView: UIViewController, ImagePickerDelegate {
...
var imagePicker: ImagePickerController!
...
override func viewDidLoad() {
        super.viewDidLoad()
        imagePicker = ImagePickerController()
        imagePicker.delegate = self
```

And you shouldn't have any problems with your delegate methods.
The first class after your class name, right after the : is the class your class inherits from.

**Comment by iMarwan-k** [comment]
@erickva I tried your approach but I'm getting this error "type ' The class name' dose not conform to protocol 'ImagePickerDelegate'

`class ViewController: UIViewController, ImagePickerDelegate{`

**Comment by erickva** [comment]
Hi @iMarwan-k , `ImagePickerDelegate` wants you to implement the following 3 methods:

```
func doneButtonDidPress(images: [UIImage]) {
    print("Done button pressed")
}

func wrapperDidPress(images: [UIImage]) {
    print("Wrapper pressed")
}

func cancelButtonDidPress() {
    print("Cancel button pressed")
}
```

**Comment by iMarwan-k** [comment]
@erickva Thanks a lot, that helped a lot

**Comment by aliasbody** [comment]
Long time since I posted this, sorry if I didn't say anything :S
So this was the error I got: 

`Method 'cancelButtonDidPress()' with Objective-C selector 'cancelButtonDidPress' conflicts with method 'cancelButtonDidPress()' from superclass 'ImagePickerController' with the same Objective-C selector`

Then trying to handle it like this:

```
import UIKit
import ImagePicker

class VC_TabPhoto: ImagePickerController, ImagePickerDelegate {
    override func viewDidLoad() {
        self.imageLimit = 5
        self.delegate   = self

        Configuration.collapseCollectionViewWhileShot = false
        Configuration.cancelButtonTitle = ""

        super.viewDidLoad()
    }
    
    func wrapperDidPress(images: [UIImage]) {
        // SOME CODE
    }
    
    func doneButtonDidPress(images: [UIImage]) {
        // SOME CODE
    }
    
    func cancelButtonDidPress() {
        // SOME CODE
    }
}
```
Anyway, I think that a full developed solution has been merged into the code so all I have to do is way for that release, until then I'll be using my version.

**Comment by aliasbody** [comment]
This error as been solved with the latest patch, I'll close it.

**Comment by aliasbody** [comment]
The problem is still here:

![captura de ecra 2016-06-03 as 10 12 53](https://cloud.githubusercontent.com/assets/9455122/15774352/cefac870-2973-11e6-8118-6e1870c844ae.png)

**Comment by aliasbody** [comment]
I'm sorry for opening and closing multiple times but the problem is really still here:

![Uploading Captura de ecrã 2016-06-03, às 10.12.53.png…]()

**Comment by aashishdhawan** [comment]
Are you using version 1.3.0?

**Comment by aliasbody** [comment]
@aashishdhawan Yes version 1.3.0

**Comment by aashishdhawan** [comment]
the patch was pushed after version 1.3.0. So if you are using cocoapods then you need to wait for next release. Or you can just pull master branch. Or may be i can request @zenangst  to release version 1.3.1.

**Comment by aliasbody** [comment]
I was guessing that :S I will try with this for now : 

> pod 'ImagePicker', :git => https://github.com/hyperoslo/ImagePicker.git

**Comment by aliasbody** [comment]
Inded with the git version it seems to be working correctly, my bad. Thank you once again, I'll close the issue!
