### ISSUE TITLE
Crop off bottom part of the taken image

### ISSUE THREAD

**Issue by slashburn** [hyperoslo/ImagePicker#156]
First of all, **awesome library, looks really really good.**

I have one question though: 
When I take a picture, the library is not cropping the lower part off the image that is hidden by the BottomContainerView. I would like like to do that because it might look confusing if more "bottom" appears on the photo as intended.

How can I crop the lower part of the image off that is hidden by the BottomContainerView? I've looked through the code but haven't found a property or so to enforce this behaviour.

**Comment by aashishdhawan** [comment]
@slashburn Thank you for your feedback and valuable suggestion, we'll look into this in future release. 
Meanwhile if you managed to solve this for yourself, feel free to submit a pull request.

**Comment by slashburn** [comment]
I did a workaround with a UIImage extension, but I agree it would be better to include it in the project directly:

```
class func cropCameraImage(image: UIImage, viewHeight: CGFloat) -> UIImage {
        
        //The height of the bottom view in the ImagePickerCamera
        //It is specified as 101 points.  
        let imagePickerBottomContainerHeight: CGFloat = 101.0
        let contextImage = UIImage(CGImage: image.CGImage!)
        
        
        let percentage = imagePickerBottomContainerHeight / viewHeight
        let newHeight = image.size.height - percentage*image.size.height
        let cropRect = CGRect(x: 0, y: 0, width: image.size.width, height: newHeight)
        let imageRef: CGImageRef = CGImageCreateWithImageInRect(contextImage.CGImage, cropRect)!
        let croppedImage = UIImage(CGImage: imageRef, scale: image.scale, orientation: image.imageOrientation)
        
        return croppedImage
    }
```

The first parameter is the UIImage that is returned from the camera, the second is the height of the entire screen. So you would call it like in your view controller (that conforms to the ImagePickerDelegate) like so:

`let croppedImages = UIImage.cropCameraImage(image, self.view.frame.height)`

**Comment by choutiy** [comment]
did anyone figure out how to achieve this one?

**Comment by onmyway133** [comment]
@slashburn @choutiy Hi, this is a valid concern. While some people find it confused not to crop the lower part, other people actually want to take image full screen. This was by design so we don't plan to change it, in the mean time @choutiy you can take a look at what @slashburn suggested
