### ISSUE TITLE
Crash with ipad 2 - camera doesn't support

### ISSUE THREAD

**Issue by Zakaru** [hyperoslo/ImagePicker#160]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** Can't add <AVCaptureDeviceInput: 0x17f6e0f0 [***]> because the device does not support AVCaptureSessionPreset1920x1080.  Use -[AVCaptureDevice supportsAVCaptureSessionPreset:].'

**Comment by zenangst** [comment]
Hey @Zakaru, which version of ImagePicker are you using? I think this has been reported before; https://github.com/hyperoslo/ImagePicker/issues/124

Try doing `pod update` just to make sure that you are on the latest version `1.3.0` :)

**Comment by Zakaru** [comment]
Thank you, it's fixed.

**Comment by onmyway133** [comment]
@Zakaru Thanks 😄
