### ISSUE TITLE
error "type 'viewcontroller' does not conform to protocol 'ImagePickerDelegate'"

### ISSUE THREAD

**Issue by StevenWhitey** [hyperoslo/ImagePicker#164]
class ViewController: UIViewController, ImagePickerDelegate, UINavigationControllerDelegate 

Im get the error "type 'viewcontroller' does not conform to protocol 'ImagePickerDelegate'"

I'm using swift.

Is there a step by step guide in installing ImagePicker after I've installed the pod?

Thanks

**Comment by aashishdhawan** [comment]
@StevenWhitey That should not happen. Could you please confirm that you are using workspace project `project.xcworkspace` and not `project.xcodeproj`?

**Comment by aashishdhawan** [comment]
@StevenWhitey Please implement protocol `ImagePickerDelegate` or just add these functions to your view controller 
```swift 

    //delegate methods

  func wrapperDidPress(imagePicker: ImagePickerController, images: [UIImage]) {
  }

  func doneButtonDidPress(imagePicker: ImagePickerController, images: [UIImage]) {
  }

  func cancelButtonDidPress(imagePicker: ImagePickerController) {
  }

```

**Comment by StevenWhitey** [comment]
Yeah I had not put the 'func' s in yet but I got it figured out. Sorry I'm new to coding. If you wouldn't mind helping me.. what code would I put the doneButtonPress to change the imageview to the selected images?

**Comment by aashishdhawan** [comment]
So when you press done button in `ImagePicker` it returns all selected images in form of array named `images`. Now you can choose any one of those images, for example, lets say you want to select first image then you can do it like this.

func doneButtonDidPress(images: [UIImage]) {
    myImageView.image = images[0]
  }

**Comment by StevenWhitey** [comment]
Awesome  thanks!!!

**Comment by aashishdhawan** [comment]
@StevenWhitey i hope this helps. Enjoy this library. let me know if you face any other issue. Always happy to help.

**Comment by zenangst** [comment]
![giphy-22](https://cloud.githubusercontent.com/assets/57446/15719588/d7cada92-2830-11e6-9350-73e7779299cc.gif)

**Comment by kbendelow** [comment]
Hey there. I'm also having the delegate problem. If i implement the protocol "ImagePickerDelegate" then I get an error saying "Type ViewController does not conform to protocol 'ImagePickerDelegate' ". If I remove the delegate from my class ViewController then I get an error saying I cannot assign value of type 'ViewController' to type 'imagePickerDelegate' ". I have added the 3 funcs and a;m in the workspace, not the xcodeproj. Any suggestions?

**Comment by beckp** [comment]
Same thing as kbendelow.

**Comment by eligreg** [comment]
Same thing happening to bckp & kbendelow is happening for me as well. Any thoughts on why this might be?

> Swift 3
> XCode 8
> iOS 10

**Comment by aashishdhawan** [comment]
@kbendelow  @beckp @eligreg Does this work for you? This example is for `ImagePicker 2.0.0, Swift 3.0.1, iOS 10`

```swift
import UIKit
import ImagePicker

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        let imagePickerController = ImagePickerController()
        imagePickerController.delegate = self
        
        //Present ImagePickerController
    }
}

extension ViewController: ImagePickerDelegate {

    func wrapperDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
    }
    
    func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
    }
    
    func cancelButtonDidPress(_ imagePicker: ImagePickerController) {
    }
}
```
