### ISSUE TITLE
Done/Cancel button closes the Window

### ISSUE THREAD

**Issue by aliasbody** [hyperoslo/ImagePicker#167]
Hello,
I have the Git version with the latest revisions, but here is the issue. I am handling the Done and Cancel button with two methods (which are mandatory because of the ImagePickerDelegate).

Now instead of just doing the code inside those functions it also executes the one from the ImagePickerController, so the result is a done button which opens performs my segue but then closes it because of the code inside the function:
```
func doneButtonDidPress() {
    let images = ImagePicker.resolveAssets(stack.assets)
    delegate?.doneButtonDidPress(self, images: images)
    dismissViewControllerAnimated(true, completion: nil)
  }
```
Those functions should be overridable at least. The only thing that solves my problem is to comment the dismiss function on both.
Here is my code:
```
import UIKit
import ImagePicker

class VC_TabPhoto: ImagePickerController, ImagePickerDelegate {
    override func viewDidLoad() {
        self.imageLimit = 5
        self.delegate   = self

        Configuration.collapseCollectionViewWhileShot = false
        Configuration.cancelButtonTitle = ""
        
        Configuration.indicatorView     = UIImageView(image: UIImage(named: "Photo_Arrow")!)
        Configuration.indicatorHeight   = 15

        super.viewDidLoad()
    }
    
    func wrapperDidPress(imagePicker: ImagePickerController, images: [UIImage]) {
        // SOME CODE
    }
    
    func doneButtonDidPress(imagePicker: ImagePickerController, images: [UIImage]) {
        // SOME CODE

        self.performSegueWithIdentifier("segueToPhotoDoneStart", sender: self)
    }

    func cancelButtonDidPress(imagePicker: ImagePickerController) {
        // SOME CODE
    }
}
```

**Comment by aashishdhawan** [comment]
It is logical to dismiss image picker on cancel, however we not doing dismiss on done (which i do not prefer.) However latest patch will give you control on done button tap. Please use latest pull.

**Comment by aliasbody** [comment]
Seems right. Thank you!
