### ISSUE TITLE
Crash on iOS 7 for using unavailable API

### ISSUE THREAD

**Issue by wongzigii** [hyperoslo/ImagePicker#169]
https://github.com/hyperoslo/ImagePicker/blob/3ae081f345898761f94ca791b17aea1bd0ef5a30/Source/AssetManager.swift#L14

I've noticed that `AssetManager` is using this API compatible with iOS 8.

    @available(iOS 8.0, *)
    public /*not inherited*/ init?(named name: String, inBundle bundle: NSBundle?, compatibleWithTraitCollection traitCollection: UITraitCollection?)

This will crash on iOS 7 device. Please fix it !

**Comment by onmyway133** [comment]
@wongzigii I think we support iOS 8+ in the podspec https://github.com/hyperoslo/ImagePicker/blob/master/ImagePicker.podspec

**Comment by wongzigii** [comment]
@onmyway133  Well, closed it.
