### ISSUE TITLE
The shutter button is not very rounded.

### ISSUE THREAD

**Issue by 5amfung** [hyperoslo/ImagePicker#170]
Not sure if my eyes are super sensitive, but running the demo in the simulator, the edge of the shutter button (the circle) isn't exactly rounded and smooth.  The edge seems like a 1x image stretched to a 3x display.

**Comment by diogoAntunes** [comment]
Thats probably because there is only **x3** images in the project and that 'causes a resize to the devices that use **x2**.

In my opinion we should create an Asset Catalog and include it on the resource bundles of the cocoapods. Any opinions? :bowtie:

**Comment by aashishdhawan** [comment]
@5amfung  The circle shutter button does not use any image and is created using only code. Please run demo on device or in simulator with 100% size.
