### ISSUE TITLE
Only show photo library

### ISSUE THREAD

**Issue by DiscoverPioneer** [hyperoslo/ImagePicker#173]
Is there a way, or could there be a way of hiding the camera and only showing a collectionview of photos taking up the entire screen?

**Comment by mrimadali** [comment]
@RamonGilabert I'm using ImagePicker Library, Is there any way to show only photos and hide camera ?

**Comment by onmyway133** [comment]
@DiscoverPioneer @mrimadali `ImagePicker` is not designed that way. One thing is that you can use https://github.com/hyperoslo/Gallery to have photos showing in a grid, and tweak the code a bit to only show the `Images` tab

**Comment by mrimadali** [comment]
@onmyway133 Thanks 👍
