### ISSUE TITLE
unselect image when select another one

### ISSUE THREAD

**Issue by iMarwan-k** [hyperoslo/ImagePicker#174]
Hi, so I make the limit to be only one image the user can select, but what I want is how can I unselect the image when the user select another one and still have the restriction of selecting only one image

Thanks

**Comment by slxl** [comment]
and also, I think, for this particular case number of images selected (1) can be omitted

**Comment by bull-xu-stride** [comment]
In `ImageGalleryView` file Line 210, you can modify the code to de-select the previous one:

      if cell.selectedImageView.image != nil {
        UIView.animateWithDuration(0.2, animations: {
          cell.selectedImageView.transform = CGAffineTransformMakeScale(0.1, 0.1)
          }) { _ in
            cell.selectedImageView.image = nil
        }
        self.selectedStack.dropAsset(asset)
				return
      }
			
			// If the limit has been set and reached, remove the 'frist' selection (you can modify to remove the last if needed)
			if self.imageLimit > 0 && self.imageLimit == self.selectedStack.assets.count {
				if let last = self.selectedStack.assets.first, item = self.assets.indexOf(last) {
					let ip = NSIndexPath(forItem: item, inSection: 0)
					if let c = collectionView.cellForItemAtIndexPath(ip) as? ImageGalleryViewCell {
						UIView.animateWithDuration(0.2, animations: {
							c.selectedImageView.transform = CGAffineTransformMakeScale(0.1, 0.1)
						}) { _ in
							c.selectedImageView.image = nil
						}
					}
					self.selectedStack.dropAsset(last)
				}
			}
				
			if self.imageLimit == 0 || self.imageLimit > self.selectedStack.assets.count {
        cell.selectedImageView.image = AssetManager.getImage("selectedImageGallery")
        cell.selectedImageView.transform = CGAffineTransformMakeScale(0, 0)
        UIView.animateWithDuration(0.2) { _ in
          cell.selectedImageView.transform = CGAffineTransformIdentity
        }
        self.selectedStack.pushAsset(asset)
			}

**Comment by iMarwan-k** [comment]
@bull-xu-stride thank you, it works perfect.

**Comment by unittesting0** [comment]
@bull-xu-stride can we let the user take a picture even though he has reached the limit (at my example just one) so the next image will get selected and the old one unselected.

**Comment by pinglamb** [comment]
To me, this case seems valid when the `imageLimit` is 1.

I modified @bull-xu-stride to be Swift 3 friendly:

```
      if self.imageLimit > 0 && self.imageLimit == self.selectedStack.assets.count {
        if let last = self.selectedStack.assets.first, let item = self.assets.index(of: last) {
          let ip = IndexPath(row: item, section: 0)
          if let c = collectionView.cellForItem(at: ip) as? ImageGalleryViewCell {
            UIView.animate(withDuration: 0.2, animations: {
              c.selectedImageView.transform = CGAffineTransform(scaleX: 0.1, y: 0.1)
            }) { _ in
              c.selectedImageView.image = nil
            }
          }
          self.selectedStack.dropAsset(last)
        }
      }
```

**Comment by dbmrq** [comment]
Oops, I didn't realize all those commits would show up here, sorry.

In my fork I set the shutter button to only show the number of images selected when it's greater than 1. Ideally I think the button should be passed the `imageLimit` so it can hide the number of images only when `imageLimit == 1`.

Also another thing to consider is that besides unselecting an image when another is selected it would be nice if the last image were unselected when the user tried to take a picture too. Right now he just can't take it, but I think he should be able to, and then that image would become the only image selected.

**Comment by aashishdhawan** [comment]
There are 2 cases for user.

1. When ImageLimit > 1
In this case we need to deselect an image whenever user tries to select an image beyond image limit. Now the rule to deselect can be different for different people. Some might want to deselect first image, some might want to deselect last image or some people might not want this feature at all because they might think this is confusion for user (include me in this group).

2. When image limit = 1
Here this request makes more sense but even then i think current behavior is not too cumbersome to handle. 

Now i think we should avoid forcing our decision to all users. If there is something peculiar to your needs, you can always fork as @dbmrq  did. 

But i really appreciate help provided by @bull-xu-stride @dbmrq @pinglamb, really great community. 

Thanks.
