### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by anthonycastelli** [hyperoslo/ImagePicker#177]
Are there any plans to support videos in the future?

**Comment by RobertNNms** [comment]
+1

**Comment by Seb-AS** [comment]
+1

**Comment by Yoloabdo** [comment]
+1

**Comment by onato** [comment]
PR: https://github.com/hyperoslo/ImagePicker/pull/283

**Comment by zenangst** [comment]
#283 was just merged, could you guys point to `master` and take it for a spin. I'll close this issue for now! 😎
