### ISSUE TITLE
How to make front camera the default

### ISSUE THREAD

**Issue by devJoshLopez** [hyperoslo/ImagePicker#178]
Hello! I am liking your library. How can I make the front camera the default? My imagepicker is for selfies but it always opens with the rear camera on.

**Comment by mehfuzh** [comment]
I am having the same issue

**Comment by aashishdhawan** [comment]
@devJoshLopez @mehfuzh This functionality has been added in commit e239eed36555cbac79d7da21eab2cddd153b3af8. But unfortunately this is not available in latest release `2.0.0` but will come in next release. Meanwhile you can use latest commit if you still need this.
