### ISSUE TITLE
AVCaptureSessionPreset is wrong

### ISSUE THREAD

**Issue by weakfl** [hyperoslo/ImagePicker#181]
I think `AVCaptureSessionPresetPhoto`should be first in `preferredPresets()`.

From Apple's documentation:

> AVCaptureSessionPresetPhoto
> Specifies capture settings suitable for high resolution photo quality output.
> 
> AVCaptureSessionPresetHigh
> Specifies capture settings suitable for high quality video and audio output.

Imho this also improves the preview (at least in portrait mode, but it would also apply to landscape if the suggestion from #115 gets implemented).
The resulting image with `AVCaptureSessionPresetPhoto` is 4:3 instead of 16:9. Since your preview layer is using `AVVideoScalingModeResizeAspectFill`, a 4:3 photo is a better match to what you see in the preview layer.

**Comment by onmyway133** [comment]
We're using `AVCaptureSessionPresetHigh` as it is the default value, and safest value. But we're testing and considering `AVCaptureSessionPresetPhoto` as well. Thanks for raising this out

**Comment by RamonGilabert** [comment]
@onmyway133 any updates here?

**Comment by onmyway133** [comment]
@RamonGilabert I still concern about the crash about supporting high quality preset. So this should be a configurable property

**Comment by weakfl** [comment]
I think only the iPhone 4S might have problems with this preset. So maybe check for device type (or `UIScreen.mainScreen().bounds.size.height >= 568`) and include the preset based on the check?
