### ISSUE TITLE
Image rotated 90° when taken with APN

### ISSUE THREAD

**Issue by papay0** [hyperoslo/ImagePicker#187]
When the picture is taken 'live', and saved, the picture is rotated by 90°.
But when the picture is selected from the library everything works fine. (even in the branch fix/rotation, just in case it was the purpose)

**Comment by weakfl** [comment]
Why has this issue been closed?

It can be easily reproduced with version 1.4. Images taken in landscape mode have wrong orientation. This was probably introduced by locking orientation to portrait mode in 1.4.
