### ISSUE TITLE
I am getting errors with the new version 

### ISSUE THREAD

**Issue by ilvcs** [hyperoslo/ImagePicker#189]
Previously it was working fine but i am getting this new erros now. Please help me .
<img width="747" alt="screenshot 2016-08-04 13 04 34" src="https://cloud.githubusercontent.com/assets/10565544/17393906/094d63d8-5a44-11e6-9f8b-8af4c12d15ee.png">

**Comment by onmyway133** [comment]
@ilvcs Hi, as of https://github.com/hyperoslo/ImagePicker/pull/163

`ImagePickerDelegate` methods have been renamed to better indicate the sender. You need to implement the correct methods

**Comment by ilvcs** [comment]
I haven't find anything new in the documentation. Can you please let me know where can i find them? Or what changes i can made with my code.

Thanks for helping.
