### ISSUE TITLE
Image Cropper

### ISSUE THREAD

**Issue by julianpomper** [hyperoslo/ImagePicker#192]
I love your ImagePicker thank you for that! It would be nice when there is a possibility to crop the image, with this nice UI. 👍 :)

**Comment by brightfuture** [comment]
Same here! Looking forward to a same style cropper.

**Comment by mradzinski** [comment]
Yep, this would be a great addition

**Comment by hth** [comment]
Seriously, this will make ImagePicker my favorite library 👍

**Comment by RamonGilabert** [comment]
I like the idea. We even have a [project](https://github.com/hyperoslo/ImageCrop) within the company for Android doing what you mentioned.

That being said, I think that would go in the scope of another library combined with this one. The same way as for a [Lightbox](https://github.com/hyperoslo/Lightbox). In my opinion, huge libraries that are a jack of all trades don't perform as well as one tiny library that does its job in a super nice way :)

With that being said too, I don't discard taking the idea and making an open source project out of it as we did on Android. :)

For the record: @hyperoslo/ios.

**Comment by hth** [comment]
Bloated library is not good. I am in sync with you on `Cropping Images` is completely a different task than what `ImagePicker` library is intended to do. There are libraries that specializes just in cropping and it makes less sense to re-invent when solution exists. 

I would prefer a solution where external libraries can work seamlessly with other libraries. It's easier said than done. [TOCropViewController](https://github.com/TimOliver/TOWebViewController) by @TimOliver is one of the top library that does supports cropping. If you guys talk and can make this happen, it will be a boon to the community.

**Comment by onmyway133** [comment]
@hth you link to the incorrect one, I think you mean https://github.com/TimOliver/TOCropViewController

**Comment by hth** [comment]
@onmyway133 Corrected link. Thanks for pointing it out.

**Comment by RamonGilabert** [comment]
I'm going to close the issue for now, as this is part of another library. We'll update here if there's any news in the upcoming library for cropping images! :)

**Comment by ManueGE** [comment]
In case anyone is interested on this, I use a class that put together **ImagePicker** and **TOCropViewController**. You can find it [here](https://gist.github.com/ManueGE/f1f3f34a8b3c7fab8d0b974a60011f60)

**Comment by hth** [comment]
Nice! I would certainly take a look 👍

**Comment by iOSUser110** [comment]
@ManueGE  hey this is really nice code , of combination of this two library, 
Can you provide code snippet for  additional feature of Zoom in Zoom out along with above two ? Image Picker,Cropper ,Zoomer ??

**Comment by musbaalbaki** [comment]
+1
