### ISSUE TITLE
crash on start with ios 10, swift 3 xcode 8

### ISSUE THREAD

**Issue by Harper04** [hyperoslo/ImagePicker#198]
Hi,

i converted the code to swift3 and added the project to my project.
Next i added the ImagePicker.framework to LinkedFrameworks and Libraries (i am using the ImagePicker in an extension)

Unfortunately it crashes on startup with this:
```
dyld: Library not loaded: @rpath/ImagePicker.framework/ImagePicker
  Referenced from: /private/var/containers/Bundle/Application/fgfgdfg-fdgdf-gdf-g-dfg-dfg-/sfgfsgdfg.app/PlugIns/MessagesExtension.appex/MessagesExtension
  Reason: image not found
```

Any hints about what i could try?

**Comment by onmyway133** [comment]
@Harper04 Hi, can you try with `Copy File Build Phase` with `Destination` set to `Frameworks`?

**Comment by thangpq264** [comment]
I have issue in AssetManager.swift.
It crashed because resourceBundle = nil.
`let bundlePath = (bundle.resourcePath)! + "/ImagePicker.bundle"
    let resourceBundle = Bundle(path: bundlePath)
    bundle = resourceBundle!`
I don't know why. Please help.

**Comment by jonnyleeharris** [comment]
This still seems to be happening on the swift 3 branch.

**Comment by minikin** [comment]
+1

**Comment by RamonGilabert** [comment]
I'll be doing a Swift 3 branch by tomorrow. I'll keep you posted :)

**Comment by RamonGilabert** [comment]
Fixed, y'all.

![screen shot 2016-09-29 at 10 55 32 am](https://cloud.githubusercontent.com/assets/6138120/18947585/02c32982-8634-11e6-9b8d-7b8b264eb27e.png)

**Comment by jonnyleeharris** [comment]
I can successfully get this screen to show but I'm hitting a crash immediately. This is running on an iPhone 6 with iOS 10.0.2. It also happens on the simulator.

<img width="1785" alt="screenshot 2016-09-30 18 40 05" src="https://cloud.githubusercontent.com/assets/1674502/19001064/81b4ded4-873d-11e6-9608-473e5257c5d6.png">

**Comment by RamonGilabert** [comment]
There are new privacy settings you need to add to your plist. Make sure that's not the problem.

**Comment by jonnyleeharris** [comment]
Thank you @RamonGilabert 

I can confirm that it works perfectly when I add the

`<key>NSPhotoLibraryUsageDescription</key>`

key to my plist.

Thanks!
