### ISSUE TITLE
AVAudioSession problem

### ISSUE THREAD

**Issue by hedtech** [hyperoslo/ImagePicker#199]
Hello,

Thanks for this module which is very useful.
However if an audio session is already active in the app, dismissing the ImagePicker controller will throw an exception and pause the music.

Any solutions for this,
Best regards,

**Comment by onmyway133** [comment]
@hedtech Hi, it would be great if you can show here that exception? And by `audio session is already active in the app`, what API to you use to activate that?

**Comment by onmyway133** [comment]
Closing for inactive issue. Feel free to reopen it if it is still the same issue to you @hedtech
