### ISSUE TITLE
is it works on swift3?

### ISSUE THREAD

**Issue by yoohoogun114** [hyperoslo/ImagePicker#208]
When i install with carthage,

```
$ carthage update
```
it failed.

log is here

2922 === CLEAN TARGET ImagePicker-iOS OF PROJECT ImagePicker WITH CONFIGURATION Release ==     =

2924 Check dependencies

2925 “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured corr     ectly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…     ] menu to choose a Swift version or use the Build Settings editor to configure the bu     ild setting directly.

2926 “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured corr     ectly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…     ] menu to choose a Swift version or use the Build Settings editor to configure the bu     ild setting directly.

2927 warning: no umbrella header found for target 'ImagePicker-iOS', module map will not b     e generated

2929 === BUILD TARGET ImagePicker-iOS OF PROJECT ImagePicker WITH CONFIGURATION Release ==     =

2931 Check dependencies

2932 “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured corr     ectly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…     ] menu to choose a Swift version or use the Build Settings editor to configure the bu     ild setting directly.

2933 “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured corr     ectly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…     ] menu to choose a Swift version or use the Build Settings editor to configure the bu     ild setting directly.

2934 warning: no umbrella header found for target 'ImagePicker-iOS', module map will not b     e generated

**Comment by RamonGilabert** [comment]
Hey, someone made a branch. I believe that by pointing your `Cartfile` to the `"swift-3"` branch you should be good.

Feel free to reopen the issue if not!
