### ISSUE TITLE
GalleryView gets detached in landscape mode

### ISSUE THREAD

**Issue by weakfl** [hyperoslo/ImagePicker#209]
When dragging the GalleryView in landscape mode, it moves in the wrong direction and floats in the middle of the screen (see below).
This happened on an actual device with iOS 10, couldn't reproduce it with iOS 9 simulator.

![imagepicker](https://cloud.githubusercontent.com/assets/614985/18779624/12a982a6-817a-11e6-9fa1-fc27d3495ead.png)

**Comment by weakfl** [comment]
This is most likely an iOS 10 issue. The whole App shows strange rotation behaviour after transitioning from a background state. Closing.

**Comment by onmyway133** [comment]
@weakfl 

> transitioning from a background state

You mean after returning to app and the phone is in landscape at that time?

**Comment by weakfl** [comment]
It doesn't matter if the phone is in landscape when returning to the app. The status bar starts rotating even on ViewControllers with portrait only, and somehow that effects the ImagePicker.

However, I've checked an older version of my app which doesn't even include your ImagePicker and it shows the same strange behaviour. I'll have to investigate what is causing it, but it's definitely not an ImagePicker issue.

**Comment by onmyway133** [comment]
@weakfl Your problem sounds similar to https://github.com/onmyway133/notes/issues/2

**Comment by weakfl** [comment]
@onmyway133 Thanks, I've actually found your comment looking for possible solutions and I am in fact creating the `UIWindow` in code, just like you described. However, I'm not specifying any `Main Interface`, so I've no idea what is causing the issue atm.
