### ISSUE TITLE
Local paths to images

### ISSUE THREAD

**Issue by Oleksandren** [hyperoslo/ImagePicker#210]
How can I get local paths to returned images:
func doneButtonDidPress(imagePicker: ImagePickerController, images: [UIImage])

**Comment by Oleksandren** [comment]
Found solution:
http://stackoverflow.com/a/35099857

**Comment by mohanmoorthy** [comment]
FYI

  func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
        
        
        imagePicker.dismiss(animated: true, completion: nil)
        
        for imageAsset in imagePicker.stack.assets {
            let options = PHContentEditingInputRequestOptions()
            options.isNetworkAccessAllowed = true
            imageAsset.requestContentEditingInput(with: options) { (contentEditingInput: PHContentEditingInput?, _) -> Void in
                
                print(contentEditingInput!.fullSizeImageURL!)
                
                //  let fullImage = CIImage(contentsOf: contentEditingInput!.fullSizeImageURL!)
                // print(fullImage!.properties)
            }
        }
    }
