### ISSUE TITLE
Static image if using in two or more places

### ISSUE THREAD

**Issue by pluckq** [hyperoslo/ImagePicker#212]
Using in two different vc cause static picture on one of them, when call imagePicker, just last seen image from camera, not even captured, like static snapshot from camera from last session
While on one of them all work ok

**Comment by zenangst** [comment]
Are both view controllers instantiated and in memory at the same time? Best guess is that both are trying to use the same session for `AVCaptureVideoPreviewLayer` which would cause one of them to fail.

Just out of curiosity, why would you need two `ImagePicker` instances in your application?

**Comment by pluckq** [comment]
I have to use it in profile vc and send photos vc, now i guess i will do singletone to solve this
