### ISSUE TITLE
SWIFT 3 Errors

### ISSUE THREAD

**Issue by hemant3370** [hyperoslo/ImagePicker#215]
` let queue = DispatchQueue(label: "no.hyper.ImagePicker.Camera.SessionQueue", attributes: dispatch_queue_attr_make_with_qos_class(DispatchQueue.Attributes(), DispatchQoS.QoSClass.background, 0))
`
   ` if let bundlePath = (bundle.resourcePath)! + "/ImagePicker.bundle", let resourceBundle = Bundle(path: bundlePath) {
      bundle = resourceBundle
    }`

`  if fetchResult == nil {
      fetchResult = PHAsset.fetchAssets(with: .image, options: fetchOptions) 
    }`

`fetchResult?.enumerateObjects { object, index, stop in`

**Comment by RamonGilabert** [comment]
Can you explain this issue?

**Comment by RamonGilabert** [comment]
I believe this is fixed in the `swift-3` branch.
