### ISSUE TITLE
cocoapods does not appear to installing the Swift 3 version

### ISSUE THREAD

**Issue by hou1nxb** [hyperoslo/ImagePicker#217]
Migrating a project to Swift 3. Updated cocoapods, but the ImagePicker code installing is not the Swift 3 version. Is this related to kzyryanov's issue needing this:

s.pod_target_xcconfig = { 'SWIFT_VERSION' => '3.0' }

in the podspec? Thanks.

**Comment by zenangst** [comment]
Hey @hou1nxb, I just added this line to the podspec. Try it now ^^

**Comment by hou1nxb** [comment]
@RamonGilabert  - I still could not get the Swift 3 code to install using 'pod ImagePicker'
I was able to get it to install using:
pod 'ImagePicker', :git => 'https://github.com/hyperoslo/ImagePicker.git', :branch => 'swift-3'
and everything compiles.
Its like cocoapods is pointing to different branch? Not sure.
Now I am getting a message saying ImagePicker was created with an older version of compiler and to rebuild ImagePicker???

**Comment by zenangst** [comment]
@hou1nxb have you tried to remove your cocoapods cache?

https://gist.github.com/mbinna/4202236

Let us know if that helps.

**Comment by ZacharyKhan** [comment]
I'm running into the same issue, it's defaulting to release 1.4.0
