### ISSUE TITLE
Crash on device (10.0.1) + Swift 3 / AssetManager lines 31 - 33

### ISSUE THREAD

**Issue by adamdahan** [hyperoslo/ImagePicker#218]
Crash on device (10.0.1) + Swift 3 / AssetManager lines 31 - 33
fatal error: unexpectedly found nil while unwrapping an Optional value

Seems to be issue with the resource bundle being created from corrupt bundle path. 
This is using cocoapods as integration

Cheers

**Comment by RamonGilabert** [comment]
That doesn't happen using the `swift-3` branch, is it? In there we removed the force unwrapping that we had. Check it out and feel free to reopen it if it still does! :)
