### ISSUE TITLE
Discuss about Swiftlint in build script

### ISSUE THREAD

**Issue by huy-le** [hyperoslo/ImagePicker#221]
Hi team,

My experience in the first time I use your library is that it cannot build by Carthage in the first time I run `carthage update`. Because ImagePicker has a build script that uses `Swiftlint`. 

Others team will have a different rule for Swiftlint, and some rule will cause an error when you build ImagePicker.

In my opinion, whether the library shouldn't depend on Swiftlint, and library's build script should be run in development mode only.

How do you think?

Cheers,

**Comment by zenangst** [comment]
Hey @huy-le, I totally see how this can cause problems. I'm gonna investigate if we can set an `ENV` value that we can check for to know when to run `swiftlint` and when to skip it. I think that should be possible without to much work. Maybe `Carthage` even sets it's own when building.

**Comment by onmyway133** [comment]
@huy-le Hi, `swiftlint` "should" use the `.swiftlint.yml` from the directory in which `swiftlint` is run, in this case it is `Carthage/ImagePicker`.

There's an old issue on Carthage about `carthage update` causing `swiftlint` to pick up the wrong `.swiftlint.yml`, but it's pretty old carthage version https://github.com/realm/SwiftLint/issues/554

If this is still a problem with you, maybe we need to explicitly specify the correct `.swiftlint.yml` in `ImagePicker` 's build phase

**Comment by onmyway133** [comment]
@huy-le closing this for now. Feel free to reopen it if it's still a problem with you
