### ISSUE TITLE
Module compiled with Swift 2.3 cannot be imported in Swift 3.0

### ISSUE THREAD

**Issue by kutran** [hyperoslo/ImagePicker#223]
I tried to include this is a Swift 3.0 project and get an error.

- Use Legacy Swift Language Version: "Yes" will result the error.
- Use Legacy Swift Language Version: "No" will result in the ImagePicker project with 204 Issues.

**Comment by RamonGilabert** [comment]
Version `2.0.0` of ImagePicker is in Swift 3. Just point to that version instead! 😊

**Comment by kutran** [comment]
Okay, so

pod 'ImagePicker', '~> 2.0'

Worked since pod 'ImagePicker', '~> 2.0.0' did not work.
