### ISSUE TITLE
❓Disable location services❓

### ISSUE THREAD

**Issue by ferologics** [hyperoslo/ImagePicker#225]
How can I force ImagePicker to not request location services?

**Comment by onmyway133** [comment]
@ferologics Hi, on the Configuration object https://github.com/hyperoslo/ImagePicker/blob/master/Source/Configuration.swift#L43, there is `recordLocation` that you can change

**Comment by ferologics** [comment]
I was looking through the source but didn't notice the Configuration.swift file, this was quite obvious.

awesome! thanks a lot. :)

**Comment by bymafmaf** [comment]
The provided solution works but I installed it with CocoaPods, so changing a file in the library would break cocoapods integrity, e.g. when I pull from source control and do `pod install` it wouldn't be the same app and developer has to change it manually.

Can you make it a property like image limit that can be changed when it's initiated?

**Comment by zenangst** [comment]
@bymafmaf the `var` in question is `static` so you can change it without touching the source code.

I think something like this should work.
```swift
ImagePicker.Configuration. recordLocation = false
```
