### ISSUE TITLE
Do tableViewControllers work with ImagePicker?

### ISSUE THREAD

**Issue by craigpearce5** [hyperoslo/ImagePicker#227]
I used cocoapods to add the pod (`pod 'ImagePicker', '~> 1.4.1'`), imported ImagePicker and added the following code.

```
let imagePickerController = ImagePickerController()
imagePickerController.delegate = self //error here
presentViewController(imagePickerController, animated: true, completion: nil)
```

I get the following error when trying to run the app.  `Cannot assign value of type 'tableViewController' to type 'ImagePickerDelegate?`.  When I add `ImagePickerDelegate` it throws the error that tableViewController does not conform to ImagePickerDelegate.
I added the 3 functions as recommended in another issue but that doesn't work.

Any help?

**Comment by onmyway133** [comment]
@craigpearce5 Hi, can you show us what delegate methods that you implement?

As of 1.4.1, the delegate methods are, as for your reference 

```swift
@objc public protocol ImagePickerDelegate: class {

  func wrapperDidPress(imagePicker: ImagePickerController, images: [UIImage])
  func doneButtonDidPress(imagePicker: ImagePickerController, images: [UIImage])
  func cancelButtonDidPress(imagePicker: ImagePickerController)
}
```

**Comment by craigpearce5** [comment]
I had tried the following in but added {} to the end.  

    func wrapperDidPress(imagePicker: ImagePickerController, images: [UIImage])
    func doneButtonDidPress(imagePicker: ImagePickerController, images: [UIImage])
    func cancelButtonDidPress(imagePicker: ImagePickerController)

Also tried as per [this issue](https://github.com/hyperoslo/ImagePicker/issues/164)

    func wrapperDidPress( images: [UIImage]) {
    }
    
    func doneButtonDidPress(images: [UIImage]) {
    }
    
    func cancelButtonDidPress() {
    }

Everything seems to result in errors.

**Comment by onmyway133** [comment]
@craigpearce5 Hi, as of ImagePicker 2.0.0 which supports Swift 3, the delegate methods slightly change. You can see the answer by @aashishdhawan here https://github.com/hyperoslo/ImagePicker/issues/164. Hope it helps
