### ISSUE TITLE
Present ImagePicker Can Be Slow 

### ISSUE THREAD

**Issue by IceFireCreations** [hyperoslo/ImagePicker#229]
If there an option or setting I am missing?

**Comment by RamonGilabert** [comment]
Can you provide more information?

**Comment by IceFireCreations** [comment]
Sure when using latest pod image piker loads fine with self.present but when updating pod to match latest commit so camera can load at front sel.present takes about 3 to 4 seconds

**Comment by aashishdhawan** [comment]
This is a duplicate of #243. Closing this, in order to keep issues list clean.
