### ISSUE TITLE
iCloud Photo Library Support

### ISSUE THREAD

**Issue by Abel7x** [hyperoslo/ImagePicker#230]
When I choose a picture that hasn't been downloaded from iCloud it returns an empty array in the delegate method.

**Comment by sifrah** [comment]
+1 for this issue. by the way, is it possible to disable iCloud album ? Thanks.

**Comment by hivakun** [comment]
+1 for this issue. I would like to disable iCloud albums too. Is that possible? Thanks.

**Comment by zenangst** [comment]
This seems like a really nice feature to have, if anyone is up for investigating this and making a PR, we would gladly review it :)

**Comment by onmyway133** [comment]
@Abel7x @sifrah @hivakun Hi, sorry for late reply. Correct me if I'm wrong but according to `PHAsset.fetchAssets(with: .image, options: options)`

> By default, fetch results **do not** include photos synced to the device through iTunes or stored in iCloud Shared Albums. To change this behavior, use the includeAssetSourceTypes property in the options parameter.

**Comment by onmyway133** [comment]
This may be solved by https://github.com/hyperoslo/ImagePicker/issues/262
