### ISSUE TITLE
Crash due to privacy violation.

### ISSUE THREAD

**Issue by gokhanakkurt** [hyperoslo/ImagePicker#231]
Hi,

I've faced a problem while integrating `ImagePicker` to my project. I followed the steps as you stated and I integrated lib to my project. However, my app is crashing due to privacy violation. 

Following code snippets illustrate how I call `ImagePickerController`

```swift
let imagePickerController = ImagePickerController()
imagePickerController.delegate = self
present(imagePickerController, animated: true, completion: nil)
```
delegate functions 

```swift
func wrapperDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
    print("wrapperDidPress")
}

func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
    print("doneButtonDidPress")
}

func cancelButtonDidPress(_ imagePicker: ImagePickerController) {
    print("cancelButtonDidPress")
}
```
Here is the snapshot of the crash

![screen shot 2016-11-10 at 17 12 25](https://cloud.githubusercontent.com/assets/3924230/20179854/a9ffb7c2-a760-11e6-949b-4c228b7800eb.png)

Do I have to handle camera permissions by myself in my app?

Btw: I'm using `XCode 8.1` and `Swift 3.0` as programming language

**Comment by gokhanakkurt** [comment]
This is my fault. I just added a description for `Privacy - Camera Usage Description` in `Info.plist` file.

**Comment by zenangst** [comment]
@gokhanakkurt 🍻

**Comment by dbmrq** [comment]
It would be nice if there were something about this in the readme. It took me a while to figure out what was going on.

**Comment by musbaalbaki** [comment]
+1
