### ISSUE TITLE
Circular image overlay?

### ISSUE THREAD

**Issue by Thegasman2000** [hyperoslo/ImagePicker#232]
I want to use this library to select, or take, and profile picture. Currently It works great and we clip the resulting image to bounds to make a circle. Can I use a custom overlay when taking, or selecting, the image? It makes a big difference when you take a photo knowing its for a circle! 

Thanks for a great library!

**Comment by Thegasman2000** [comment]
Noone?

**Comment by aashishdhawan** [comment]
@Thegasman2000 Right now `ImagePicker` does not support this functionality. This request is an enhancement which, if implemented needs to be optional because some users might not want to use circular overlay. 

We'll keep this request in mind and will update you if a future version supports this.

**Comment by zenangst** [comment]
Feel free to make a PR to add this functionality. It would be a neat addon :)

**Comment by n1mda** [comment]
https://github.com/budbee/SelfieKit

We love ImagePicker, but also wanted this functionality so we created a similar project with an assisted "face" overlay, like the one you are requesting

**Comment by onmyway133** [comment]
@n1mda congrats on the library. Closing this issue for now
