### ISSUE TITLE
issues when Presenting from landscape view

### ISSUE THREAD

**Issue by tvstuff** [hyperoslo/ImagePicker#235]
I'm trying to use to this control in landscape only application, if don't allow portrait orientation app crashed saying 
"Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [ImagePicker.ImagePickerController shouldAutorotate] is returning YES'"

When I allow  "portrait orientation" & present view from landscape view cancel & selected photo are displaced , see attached 
![simulator screen shot 15-dec-2016 4 26 32 pm](https://cloud.githubusercontent.com/assets/9385082/21222563/451d05d6-c2e4-11e6-8c59-440f39f0b7f1.png)
![simulator screen shot 15-dec-2016 4 26 39 pm](https://cloud.githubusercontent.com/assets/9385082/21222564/451ea81e-c2e4-11e6-9817-c0c58d43f8c5.png)

Ideal situation for me is to use this control in landscape only, but if that's not possible can you please tell me work around to get button & icon at it right place
thanks

**Comment by onmyway133** [comment]
@tvstuff Hi, as of https://github.com/hyperoslo/ImagePicker/pull/186. `ImagePicker` requires portrait orientation support, and in fact, it is locked to portrait only, and rotates the controls when there is orientation changes. 

If you want to display in landscape only, you can make a fork, update `supportedInterfaceOrientations` in `ImagePickerController` and relayout in `CameraView`

**Comment by onmyway133** [comment]
@tvstuff Hi, I will close this for now. Feel free to reopen it.
