### ISSUE TITLE
Collapse galleryview by default

### ISSUE THREAD

**Issue by girishghoda** [hyperoslo/ImagePicker#237]
@zenangst Hi i want collapse gallery view when open pickerview
i added below method in viewdidappar but not sucess
self.imagePicker.collapseGalleryView(action)
self.imagePicker.collapseGalleryView(nil)

Thank you

**Comment by aashishdhawan** [comment]
@girishghoda  Please try this and let me know if this solves your problem. You can subclass `ImagePickerController` and add your intended functionality.

```Swift
import Foundation
import ImagePicker

class DemoImageViewController: ImagePickerController {

  override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)

    collapseGalleryView(nil)
  }
}
```

**Comment by aashishdhawan** [comment]
@girishghoda  Closing this. Feel free to reopen if you are still facing this issue.

**Comment by girishghoda** [comment]
@aashishdhawan hey first thanks for reply but problem still facing
i defing let imagePicker = ImagePickerController() and in 
 override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)

    collapseGalleryView(nil)
  }
but when imagepicker open it show gallaryview

Thank you
