### ISSUE TITLE
Shutter 

### ISSUE THREAD

**Issue by jackpaster** [hyperoslo/ImagePicker#238]
@vickeryj @zenangst @cemaleker @fespinoza @nashby  How can I make this project so that if you click and hold on the camera button, a shutter or burst of images will be taken at my own desired rate. Or a continuous amount of images will be taken.

**Comment by zenangst** [comment]
Correct me if I'm wrong here @onmyway133 @RamonGilabert @vadymmarkov, but we don't have that kind of feature right now.

If you feel that the library is lacking something, feel free to submit a PR to add the feature. We love PR's and have a blast while reviewing them 🍻

**Comment by RamonGilabert** [comment]
The initial idea when holding the button was to record video, so we sould have to think in another way to do that if we want to go ahead and implement it.

**Comment by jackpaster** [comment]
@vickeryj @zenangst @cemaleker @fespinoza @nashby Could you implement it in a way where if you hold down the button, a burst of images is taken and when you let go of the button, you transition to another view controller, with all of those images in sequence. Is this possible to implement

**Comment by zenangst** [comment]
@jackpaster ohai again, this is totally possible to implement, but like we mentioned above. Feel free to make a PR and we will be happy to review it.

**Comment by jackpaster** [comment]
@zenangst Is a PR a pull request

**Comment by RamonGilabert** [comment]
Yeah, @jackpaster.

**Comment by jackpaster** [comment]
So you would like me to create the code and add it to the project for
review.

**Comment by RamonGilabert** [comment]
Yeah, @jackpaster.

**Comment by zenangst** [comment]
@jackpaster https://github.com/hyperoslo/ImagePicker/blob/master/CONTRIBUTING.md 😎
