### ISSUE TITLE
Not able to limit the imagePicker to 1

### ISSUE THREAD

**Issue by sriteja25** [hyperoslo/ImagePicker#240]
I integrated ImagePicker in my project.

i am unable to restrict the user to pick only one image from gallery. Can some one help me how exactly to acheive this ?

imagePickerController.imageLimit = 1 i used this but its not working in my application.

**Comment by aashishdhawan** [comment]
@sriteja25  I just run the example and was able to limit number of images to one.  This worked for me 

```Swift
   let imagePicker = ImagePickerController()
    imagePicker.imageLimit = 1
    imagePicker.delegate = self

    present(imagePicker, animated: true, completion: nil)
```

Are you still facing this issue? If yes, could you please share the code snippet you are using?

**Comment by aashishdhawan** [comment]
Closing this. @sriteja25  Feel free to reopen if you are still facing this issue.
