### ISSUE TITLE
open var to change bg color

### ISSUE THREAD

**Issue by gulzatique** [hyperoslo/ImagePicker#241]
hi 
May I ask you to open this var so I could change the background color? please see pic attached. thanks

<img width="593" alt="screenshot at 22 17-43-51" src="https://cloud.githubusercontent.com/assets/21258164/21424662/7cbdf6c8-c86e-11e6-8040-be6a7a228874.png">

**Comment by RamonGilabert** [comment]
It just happened: https://github.com/hyperoslo/ImagePicker/pull/239/files. Use the master branch for this. Closing the issue.

**Comment by gulzatique** [comment]
excuse me but you did also applied changes to another color which I think was wrong

now the bottomContainer.background color is equal to Configuration.mainColor& previously they could have 2 different colors

could you change it like following example?
that would be great 
 
open lazy var bottomContainer: BottomContainerView = { ......
   view.backgroundColor = Configuration.**bottomContainerColor**
   .....}()

and add this to configurations:

**public static var bottomContainerColor** = UIColor(red: 0.09, green: 0.11, blue: 0.13, alpha: 1)
