### ISSUE TITLE
colors for bottom and main are same now

### ISSUE THREAD

**Issue by gulzatique** [hyperoslo/ImagePicker#242]
Hi I have previously opened this https://github.com/hyperoslo/ImagePicker/issues/241  and it was closed by https://github.com/hyperoslo/ImagePicker/pull/239/files

But you did also apply changes to another color which I think was wrong, and here is why:

now the bottomContainer.background color is equal to Configuration.mainColor& previously they could have 2 different colors (main color is the color of cell separators :) )

could you change it like following example?
that would be great

open lazy var bottomContainer: BottomContainerView = { ......
**view.backgroundColor = Configuration.bottomContainerColor**
.....}()

and add this to configurations:

**public static var bottomContainerColor = UIColor(red: 0.09, green: 0.11, blue: 0.13, alpha: 1)**

**Comment by RamonGilabert** [comment]
Hey @gulzatique! It would be awesome if you could make a PR to fix the issue! :)

**Comment by zenangst** [comment]
What @RamonGilabert  said! 😎

**Comment by aashishdhawan** [comment]
@gulzatique This has been resolved in #246. Closing this.
