### ISSUE TITLE
Image picker presenter works really slow or crashes

### ISSUE THREAD

**Issue by gulzatique** [hyperoslo/ImagePicker#243]
image picker presents really slow when I declare let imagePickerController = ImagePickerController()
    in addPictureButton() 

But if I declare a global let imagePickerController = ImagePickerController()
then it loads faster but crashes, steps as follows:
1) press Add Picture Button
2) check image
3) press done
4) repeat step 1 again and it crashed

    what can I do about it? thanks

**Comment by gulzatique** [comment]
logs say this twice even if i press addImage button once only: 
<img width="882" alt="screenshot at 23 02-12-01" src="https://cloud.githubusercontent.com/assets/21258164/21438846/3e081764-c8b5-11e6-9fcd-08f9a4f7ecef.png">


why could this happen and how to fix it?

thanks

**Comment by jacksongan79** [comment]
i face the same problem like yours, how did u get the logs? my app crashes when i click the camera button which is linked to my func addPhotos().  

I would not say it happens all the time, sometimes it works without any problem but if i were to edit the entry and click the camera button for the second time during the same session, it would just crash. My codes below, 

@IBAction func pickPhotos(_ sender: UIBarButtonItem) {
        
        let imagePickerController = ImagePickerController()
        imagePickerController.delegate = self
        imagePickerController.imageLimit = 3
        present(imagePickerController, animated: true, completion: nil)

    }

As you can see it is really simple and straightforward.

**Comment by gulzatique** [comment]
**jacksongan79** did you include camera and library permissions in your info.plist file?
I never get it crushed, and logs come up on their own)

**Comment by jacksongan79** [comment]
yes i did , for both camera and library permissions. Hopefully we will get advice soon.

**Comment by vadymmarkov** [comment]
@gulzatique @jacksongan79 Do you have any crash logs, so we can see the full picture of what exactly is going on there? As for your warnings @gulzatique, I see you're trying to present `ImagePickerController` on `ParcelInfoVC`, are your sure it's the top most view controller in the window hierarchy?

**Comment by jacksongan79** [comment]
for my app there is no crash logs, what happened was that when i build and run it on my iPhone, it shows this (maybe not related to the imagepicker but i just share with you anyway), 
![img_7527](https://cloud.githubusercontent.com/assets/24728663/21451096/63621122-c937-11e6-9d0f-cad963c014dd.JPG)

then i have to build and run again for it to continue as normal.

For my app, the top view controller is a collection view with a "add new entry" button on the navigation bar.

As i tap on the "add new button" it will segue to a new entry VC where i can entry new data and "add new photo", the "add new photo" is where the imagepicker is. 

On the first page (the collection view controller), i can also tap on any cell to trigger didselectitem and it will segue to a detail view controller where i can edit the data, there is also a image picker button there.

Sometimes the app crashes when i want take photos for the new entry, sometimes it crashes when i want to edit the data (take new photos or choosing other photos to replace the existing one). 

i have info.plist entry for the following so i am not sure what else that i could have done. Thank you for your help.

<img width="394" alt="screen shot 2016-12-23 at 5 49 58 pm" src="https://cloud.githubusercontent.com/assets/24728663/21451214/4d00fd02-c938-11e6-9dbb-3c3c0beba5b1.png">

**Comment by jacksongan79** [comment]
for some reason the app never crash when I'm using the simulator, it only happens on the phone.

**Comment by gulzatique** [comment]
@vadymmarkov ParcelInfoVC is not the root view controller, how should I fix it?)  there are 2-3 VCs prior to the ParcelInfoVC

regarding crushing logs - no I do not have any

**Comment by jacksongan79** [comment]
In Xcode with the iPhone connected you can go to Window->Devices, select your phone and press 'View Device Logs'. You will see a list with all the last crashes of the apps and with the information of the crash.

Found the above from the web, I am viewing my logs now.

**Comment by jacksongan79** [comment]
{
  "crashReporterKey" : "67f1904d65d934fdaee21043f3114db6b32e9558",
  "kernel" : "Darwin Kernel Version 16.1.0: Thu Sep 29 21:56:12 PDT 2016; root:xnu-3789.22.3~1\/RELEASE_ARM64_S8000",
  "product" : "iPhone8,2",
  "incident" : "F245F013-05EC-45FD-8652-62093C94FEA2",
  "date" : "2016-12-23 16:17:31.94 +0800",
  "build" : "iPhone OS 10.1.1 (14B100)",
  "timeDelta" : 2,
  "memoryStatus" : {
  "compressorSize" : 74955,
  "pageSize" : 16384,
  "compressions" : 14226382,
  "memoryPages" : {
    "active" : 8274,
    "throttled" : 0,
    "fileBacked" : 5831,
    "wired" : 32448,
    "anonymous" : 6636,
    "purgeable" : 0,
    "inactive" : 3599,
    "free" : 986,

{
  "crashReporterKey" : "67f1904d65d934fdaee21043f3114db6b32e9558",
  "kernel" : "Darwin Kernel Version 16.1.0: Thu Sep 29 21:56:12 PDT 2016; root:xnu-3789.22.3~1\/RELEASE_ARM64_S8000",
  "product" : "iPhone8,2",
  "incident" : "15C94C02-FEB8-43E5-AB6D-41454638F0BC",
  "date" : "2016-12-23 16:17:31.97 +0800",
  "build" : "iPhone OS 10.1.1 (14B100)",
  "timeDelta" : 0,
  "memoryStatus" : {
  "compressorSize" : 74829,
  "pageSize" : 16384,
  "compressions" : 14226588,
  "memoryPages" : {
    "active" : 7994,
    "throttled" : 0,
    "fileBacked" : 5604,
    "wired" : 32440,
    "anonymous" : 6805,
    "purgeable" : 18,
    "inactive" : 4083,
    "free" : 1469,

{
  "crashReporterKey" : "67f1904d65d934fdaee21043f3114db6b32e9558",
  "kernel" : "Darwin Kernel Version 16.1.0: Thu Sep 29 21:56:12 PDT 2016; root:xnu-3789.22.3~1\/RELEASE_ARM64_S8000",
  "product" : "iPhone8,2",
  "incident" : "96F671D9-2AF7-4148-A40F-FCFA746798F2",
  "date" : "2016-12-23 16:17:31.07 +0800",
  "build" : "iPhone OS 10.1.1 (14B100)",
  "timeDelta" : 2,
  "memoryStatus" : {
  "compressorSize" : 74533,
  "pageSize" : 16384,
  "compressions" : 14219848,
  "memoryPages" : {
    "active" : 8782,
    "throttled" : 0,
    "fileBacked" : 5913,
    "wired" : 32394,
    "anonymous" : 7291,
    "purgeable" : 0,
    "inactive" : 4245,
    "free" : 298,

These 3 are among the crashlogs that i retrieved from my phone while using my app with the image picker.

**Comment by vadymmarkov** [comment]
@gulzatique It's not necessary for `ParcelInfoVC` be a root controller, but it should be the current visible one if you present something on top of it. But I don't see it as a reason of a crash tbh. 

@jacksongan79 Thanks for your description. I'm not 100% sure about your "Lost connection" issue, but it could be a memory issue, for instance the app is allocating a lot of memory, for example when it's loading very large images and the OS just terminates the app. Would be helpful to get crash stack trace.

I think it might be related to https://github.com/hyperoslo/ImagePicker/pull/206

**Comment by jacksongan79** [comment]
@vadymmarkov I managed to solve the problem by deleting some unrelated files as well as some photos from plist that I use to load into my app, now everything is ok and the image picker works perfectly and responsively too, thank you for spending your time on this!

**Comment by aashishdhawan** [comment]
@gulzatique is everything working for you now or are you still facing this issue?

**Comment by skynext** [comment]
Hi I've the same issue the camera picker take 4-5 seconds to appear

**Comment by kenrickvaz** [comment]
Had a similar issue. After a lot of debugging I realised it is because the gallery view is selecting ALL the images from my photos. So I hacked the code (asset manager) to show just the last 10 and it is way better. I suggest adding this as an option in the setup.

**Comment by onmyway133** [comment]
@gulzatique that could be related to your view hierarchy when you tried to present `ImagePicker`. Is it also slow when you present another ViewController, say, UIImagePickerController?

@skynext @kenrickvaz Hi, according to https://www.shinobicontrols.com/blog/ios8-day-by-day-day-20-photos-framework

> PHFetchResult has an API which looks very like NSArray, so you can iterate through the results, access results by index, and count the total number of items in the fetch result. Importantly, the items are lazy-loaded from the store in batches – i.e. the results aren’t all loaded in to memory at call-time, but are instead loaded when required. This reduces the memory footprint on something that could be a result set.

That should not block your UI, but I think we should dispatch it to background https://github.com/hyperoslo/ImagePicker/issues/253 just to be sure.
