### ISSUE TITLE
changing Cancel button title is not working

### ISSUE THREAD

**Issue by gulzatique** [hyperoslo/ImagePicker#244]
I changed cancel button title and it still shows as Cancel (code is Configuration.cancelButtonTitle = "Отменить")

but changing other titles like Done button - works fine

**Comment by richardtop** [comment]
It works for me:
```
 Swift
func buttonTouched(button: UIButton) {
    Configuration.cancelButtonTitle = "Отменить"
    let imagePicker = ImagePickerController()
    imagePicker.delegate = self

    present(imagePicker, animated: true, completion: nil)
  }
```
This is the default demo screen, I've changed  the title to yours, everything seems to work fine.

![simulator screen shot dec 27 2016 20 46 45](https://cloud.githubusercontent.com/assets/8013017/21506031/b280b290-cc75-11e6-9416-39fb259adca5.png)

**Comment by aashishdhawan** [comment]
@gulzatique Please try above example. This works. 
Let us know if you are still facing this issue.
