### ISSUE TITLE
Asynchronous image importing

### ISSUE THREAD

**Issue by vbrittes** [hyperoslo/ImagePicker#247]
The application gets stuck for a few seconds when plenty images are selected. Since the delegate methods are already implemented, async running was already expected, but it seems that it's not happening.

**Comment by onmyway133** [comment]
@vbrittes when we select an image, the most consuming time is in the updating of image stack. Does it happen on the 1st image selection, or after sometime?

**Comment by vbrittes** [comment]
It happens whenever I hit done after performing a multiple selection.

**Comment by MMOmaster35** [comment]
I have noticed the same error. Any news on fixing it?
