### ISSUE TITLE
Demo project hits Segmentation fault on compilation

### ISSUE THREAD

**Issue by kishykumar** [hyperoslo/ImagePicker#248]
I am on Xcode 8.2. When I run the example/demo project using "pod try ImagePicker",  there's a SEGV: 

    Command failed due to signal: Segmentation fault: 11

Error message from the swift command is:   

     "1.	While emitting SIL for 'localizedString' at /var/folders/rb/49lxzgts6jdc944lp47nl4wm0000gn/T/CocoaPods/Try/ImagePicker/Demo/ImagePickerDemo/Pods/Sugar/Source/Shared/Localization.swift:11:8"

Seems like we are hitting the following issue and upgrading the Sugar version will fix it. 

https://github.com/hyperoslo/Sugar/issues/91

Update: When I took the zip from the homepage and ran it, it works fine because Sugar version 3.0.0 got downloaded.

**Comment by onmyway133** [comment]
@kishykumar Hi, thanks for your report. Sugar was updated in this PR https://github.com/hyperoslo/ImagePicker/pull/233, and we just update the `podfile.lock` to reflect that. 🍷
