### ISSUE TITLE
How to unselect an image when user wants to select a new image ?

### ISSUE THREAD

**Issue by sriteja25** [hyperoslo/ImagePicker#250]
I want to unselect the selected image from the first time when user presses "Select photo" button for the second time automatically. How to achieve this.

**Comment by Markuswu** [comment]
I also want the same thing. I looked at the code, I don't think it's currently possible. This should be a new feature, I believe.

**Comment by Markuswu** [comment]
I think this PR is what you want. 
https://github.com/hyperoslo/ImagePicker/pull/245

**Comment by kevinlee85** [comment]
+1 I also need the same solution.

**Comment by kevinlee85** [comment]
Why not make one pod release?

**Comment by kevinlee85** [comment]
I saw the new pod trunk release, Thank you.

**Comment by onmyway133** [comment]
@kevinlee85 Hope that it works. Closing this for now, feel free to reopen this if you have any issues
