### ISSUE TITLE
when Installing from cocoapods xcode asks to convert from swift 2.3 to swift 3

### ISSUE THREAD

**Issue by ismyhc** [hyperoslo/ImagePicker#254]
Im using swift 3 in my current project. When installing ImagePicker from cocoapods, I get the prompt to convert ImagePicker from 2.3 to 3 syntax. Is cocoapods version not swift 3?

Any help much appreciated!

**Comment by ismyhc** [comment]
I figured out my problem. Just needed to do:

pod repo update

**Comment by onmyway133** [comment]
@ismyhc glad that you figured it out 🎉
