### ISSUE TITLE
Id like to get the PHAsset from the UIImages passed back from ImagePicker

### ISSUE THREAD

**Issue by ismyhc** [hyperoslo/ImagePicker#255]
This isn't directly related to ImagePicker, but would someone have an example of how to get the PHAsset from the UIImages passed back from the picker?

Any help much appreciated :)

**Comment by onmyway133** [comment]
@ismyhc Hi, you can access the `stack` property of `ImagePickerController`, it is an instance of `ImageStack` and has `open var assets = [PHAsset]()` that you can use

**Comment by richardtop** [comment]
Hi, @ismyhc.
You can get assets as well with a bit of manual work. `PHAssets` are stored inside the `ImageStack` class:
```Swift
  func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
    let assets = imagePicker.stack.assets
    print("Fetched \(assets.count) assets")
    imagePicker.dismiss(animated: true, completion: nil)
  }
```
Feel free to close this issue, if your question has been resolved.

**Comment by richardtop** [comment]
@onmyway133 that was quick!

**Comment by ismyhc** [comment]
@onmyway133 @richardtop After looking at the source I came to this conclusion :) I should probably investigate a bit more before posting. Sorry about that :)

Thanks for your quick replies!!

**Comment by onmyway133** [comment]
@ismyhc You're welcome. Reading source code is fun 😄
