### ISSUE TITLE
Use system fonts in the default configuration

### ISSUE THREAD

**Issue by richardtop** [hyperoslo/ImagePicker#256]
![image](https://cloud.githubusercontent.com/assets/8013017/22758389/8f9a4924-ee5f-11e6-82eb-c486408e023d.png)
Fonts supplied with iOS can be changed any time, as well as the names of the font may vary in different iOS versions. Also, the default font now is _San-Francisco_, not _Helvetica Neue_, therefore, it's better to use system fonts as the default ones.

**Comment by richardtop** [comment]
Fixed in #259

**Comment by zenangst** [comment]
@richardtop 🚀
