### ISSUE TITLE
Fail to load images from iCloud

### ISSUE THREAD

**Issue by 70mmy** [hyperoslo/ImagePicker#261]
If you choose an image that is not downloaded on the local device for some reason, like after a restore or maybe if it was taken on another device, imageManager.requestImage returns nil.

I searched around and found that adding `requestOptions.isNetworkAccessAllowed = true` in AssetManager.swift in the resolveAssets function fixes this problem.

I don't really have time to learn how to make a pull request on github (never done one), if anyone has time and considers this a valid fix please, do a pull request

**Comment by onmyway133** [comment]
@70mmy I think we can close it for now

**Comment by madhavisolanki** [comment]
I am still facing this issue. @onmyway133 @70mmy can you please help.
