### ISSUE TITLE
Change configuration access level

### ISSUE THREAD

**Issue by weakfl** [hyperoslo/ImagePicker#264]
Would you mind changing the access level of `ImagePickerController.configuration` to `open var configuration = Configuration()`?

Among other projects I'm also using `ImagePickerController` in a project with some legacy objective-c code. I've made an objective-c compatible BridgeViewController for compatibility, but I can't use the custom initializers because the BridgeViewController uses a `UIStoryboardSegue` to embed the ImagePickerController...

**Comment by onmyway133** [comment]
@weakfl This is valid concern, mind making a PR 😉

**Comment by weakfl** [comment]
Merged faster than I was able to write a comment 😁 Thanks!

**Comment by weakfl** [comment]
Seems like this change has been reverted in the latest release.
Just let me know if it was reverted on purpose, I need to fork anyway 😉 

In case it wasn't, two changes are required in `ImagePickerController.swift`:
```diff
-  let configuration: Configuration
+  open var configuration: Configuration
````

and
```diff
   public required init?(coder aDecoder: NSCoder) {
-    fatalError()
+    self.configuration = Configuration()
+    super.init(coder: aDecoder)
   }
```

**Comment by onmyway133** [comment]
@weakfl Hi, yeah it is intentional. We think that the configuration should be injected at init, and should never be mutated again to avoid confusion. Hope you understand

**Comment by weakfl** [comment]
Sure, no problem at all.
