### ISSUE TITLE
doneButtonDidPress delegate don't work

### ISSUE THREAD

**Issue by lam560** [hyperoslo/ImagePicker#267]
There is a problem with the delegate of done/cancel button, it's simply don't works. I think it's an issue with swift 3

func doneButtonDidPress(_ button: UIButton) {
    if button.currentTitle == Configuration.cancelButtonTitle {
      delegate?.cancelButtonDidPress()
    } else {
      delegate?.doneButtonDidPress()
    }
  }

**Comment by zenangst** [comment]
@lam560 did you manage to solve the issue yourself? If so, what was the problem?

**Comment by lam560** [comment]
It was my mistake, I don’t know how to delete the issue on github.

**Comment by zenangst** [comment]
@lam560 no worries mate, I was just curious 🌞
