### ISSUE TITLE
cannot reset imageLimit

### ISSUE THREAD

**Issue by youngwjung** [hyperoslo/ImagePicker#268]
func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
        imagePicker.dismiss(animated: true, completion: nil)
        for image in images {
            selectedImage.append(image)
        }
        collectionView?.reloadData()
        //imagePicker.stack.assets.removeAll()
        imagePicker.resetAssets()
        
    }

override func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let cell = collectionView.cellForItem(at: indexPath) as! PhotoSelectionCollectionViewCell
        if (cell.imageView.image?.isEqualToImage(image: UIImage(named: "imagePlaceholder")!))! {
            
            if selectedImage.isEmpty {
                imageLimit = numberOfPhotos
                //print(imageLimit!)
            } else {
                imageLimit = numberOfPhotos - selectedImage.count
                //print(imageLimit!)
            }
            imagePicker.imageLimit = imageLimit!
            print(imagePicker.imageLimit)
            present(imagePicker, animated: true, completion: nil)
        }
    }

As I need only 5 photos to be saved, Dynamically change the limit but I can still choose the 5 photos in image picker. The value of imagePicker.imageLimit changed but it does not affect the image picker selection view.

**Comment by almatri** [comment]
I have exactly the same issue.
 The value of imagePicker.imageLimit changed but it does not affect the image picker selection view.

The current solution is to declare the imagePicker each time I want to present the imagePicker like this 
    let imagePicker = ImagePickerController()
    imagePicker.delegate = self
    imagePicker.imageLimit = 5 - self.images.count
    present(imagePicker, animated: true, completion: nil)

but in this way I face delay each time I present the imagePicker when the device is full of photos !!

**Comment by prYmea** [comment]
Same problem.

```galleryView.imageLimit``` needs to be updated when that value change.
