### ISSUE TITLE
Expand gallery

### ISSUE THREAD

**Issue by johnarnaou** [hyperoslo/ImagePicker#271]
Expand to full gallery showing the images in cells like the UIImagePickerController ?

**Comment by richardtop** [comment]
@johnarnaou there are already libraries to fit your need:
https://github.com/ytakzk/Fusuma
https://github.com/wenzhaot/InstagramPhotoPicker
you can try these ones and see if they do the job.

**Comment by onmyway133** [comment]
@johnarnaou Hi, `ImagePicker` does not have this use case. Like @richardtop said, you can try other lib that show images in grid. You can also try https://github.com/hyperoslo/Gallery 😎

**Comment by johnarnaou** [comment]
Thank you!
