### ISSUE TITLE
How to zoom in and zoom out?

### ISSUE THREAD

**Issue by jjpatel1996** [hyperoslo/ImagePicker#272]
can we able to zoom in and zoom out in Camera?

**Comment by onmyway133** [comment]
@jjpatel1996 Hi, that is not supported at the moment. Feel free to make a PR and we 'd love to review

**Comment by iOSUser110** [comment]
Hey , this feature is really necessary , additional to this cropping can be provided. SO that we can stuck with one library for all related things, that means everything related to camera , gallery at on roof.
It will save lot of time  of developers
