### ISSUE TITLE
How to use Configuration struct?

### ISSUE THREAD

**Issue by kevinlee85** [hyperoslo/ImagePicker#273]
How to use Configuration struct?

**Comment by kevinlee85** [comment]
Configuration.allowMultiplePhotoSelection = false and it wraning me no that variable.

**Comment by onmyway133** [comment]
@kevinlee85 Hi, as of https://github.com/hyperoslo/ImagePicker/pull/257, the `Configuration` has been refactored to be instance instead of singleton. We 'll update the document

**Comment by kevinlee85** [comment]
Yes, Do you have one plan to make new CocoaPod release?

**Comment by onmyway133** [comment]
@kevinlee85 Hi, we just released it today https://github.com/hyperoslo/ImagePicker/releases/tag/2.1.0. Hope it help
