### ISSUE TITLE
 'Configuration' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by JesusAdolfo** [hyperoslo/ImagePicker#276]
I imported ImagePicker
and implemented the delegate.
Out of the box, the camera works fine...

However, I want to customize the texts and whenever I try to instantiate the Configuration class 
I get the following error:   'Configuration' initializer is inaccessible due to 'internal' protection level

<img width="769" alt="screen shot 2017-03-24 at 19 47 55" src="https://cloud.githubusercontent.com/assets/12354503/24316185/d5cb0784-10ca-11e7-9615-4c37c8710775.png">

Why would this happen if the Configuration Class is declared as a **public struct**?

Has anyone tried this lately on Swift 3?

The code I am using as you can see, is pretty much the same in the main page of this repo.

**Comment by onmyway133** [comment]
@JesusAdolfo Can we have a quick check about the version of ImagePicker in your `Podfile.lock`?

**Comment by JesusAdolfo** [comment]
ImagePicker (2.0.0)

**Comment by JesusAdolfo** [comment]
updating to 2.1.0 solved the issue.
