### ISSUE TITLE
'Configuration' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by caoyunxiao** [hyperoslo/ImagePicker#277]
'Configuration' initializer is inaccessible due to 'internal' protection level

**Comment by zenangst** [comment]
Hey @caoyunxiao, this seems related to https://github.com/hyperoslo/ImagePicker/issues/276

Have you tried version 2.1.0?

**Comment by caoyunxiao** [comment]
Version 2.0.0, this is the highest

**Comment by zenangst** [comment]
Oh right, we haven't made a release yet. Try pointing to `master` in the meanwhile :)

**Comment by onmyway133** [comment]
@caoyunxiao Hi, can you check again? We have release 2.1.0 https://github.com/hyperoslo/ImagePicker/releases/tag/2.1.0 and podspec 2.1.0 https://cocoapods.org/?q=imagePicker last week

**Comment by caoyunxiao** [comment]
Ok, thank you very much, hope that the framework is better

**Comment by zenangst** [comment]
I'll just go head and close this for now, let us know how it goes :)

**Comment by tjarbo** [comment]
I have the same problem again with Vers. 3.0.0 ...

**Comment by onmyway133** [comment]
@tjarbo Hi, you need to create your `Configuration` object, then pass it to `ImagePickerController` initialiser
