### ISSUE TITLE
Doing pod install pulls older version.

### ISSUE THREAD

**Issue by eman6576** [hyperoslo/ImagePicker#278]
Hi,

When doing a pod install and following the readme, it pulls version 2.0.0 which is broken because when trying to create an instance of `Configuration`, the initializer is not available. But when updating the podfile to use the GitHub url instead, the latest version is pulled and the issue with `Configuration` is fixed and the initializer is now present in the source file. Wanted to bring to your attention incase anyone else has an issue with working with `Configuration`.

**Comment by zenangst** [comment]
Have you tried running `pod update ImagePicker` or removed your `Podfile.lock` ?

**Comment by eman6576** [comment]
Yes I did and still same issue.

**Comment by zenangst** [comment]
@eman6576 have you tried running `pod repo update` ?

**Comment by ismyhc** [comment]
@eman6576 I believe @zenangst suggestion should work. `pod repo update` worked for me a while back when I had the same issue.

**Comment by DarkInnocence** [comment]
It's the same issue with me I guess. I have run pod repo update followed by pod update ImagePicker.
The terminal shows it's installing the new version but as soon as I built the project it still shows me those 3 warnings.  Any suggestions welcome.
![screen shot 2017-03-30 at 5 28 59 pm](https://cloud.githubusercontent.com/assets/26249846/24503136/6b0e3f94-156e-11e7-9bda-388c0aa98654.png)

**Comment by ismyhc** [comment]
@DarkInnocence I would imagine the next update will have the fix for this. I submitted a pull request that was accepted earlier this week. Just keep you eyes pealed for the next update.

**Comment by onmyway133** [comment]
@DarkInnocence Hi, like @ismyhc said, it is because `M_PI` is deprecated. We will check and publish a new version soon

**Comment by DarkInnocence** [comment]
Awesome, will be waiting !!

**Comment by onmyway133** [comment]
@DarkInnocence Hi, just released 2.1.1. But actually these are just warnings, not errors

**Comment by DarkInnocence** [comment]
Thanks :D
