### ISSUE TITLE
AVAudioSession Opt out

### ISSUE THREAD

**Issue by JeremieDaigle** [hyperoslo/ImagePicker#280]
Some frameworks need to use `AVAudioSession.sharedInstance` and changing the active setting can cause issues.  (example: https://www.politepix.com/openears/)

If we added an option in configurations which didn't use AVAudioSession, that would be great.

**Comment by rav3r** [comment]
I've just made pull request solving this issue: https://github.com/hyperoslo/ImagePicker/pull/310

**Comment by onmyway133** [comment]
@JeremieDaigle Hi, we just merged @rav3r 's PR. The change should be included in the next version
