### ISSUE TITLE
Support other Layout than fullscreen

### ISSUE THREAD

**Issue by benwalch** [hyperoslo/ImagePicker#282]
Thank you for this great piece of software! You guys did an awesome work.

I am using this in an iPad application, where I display the ImagePicker in a NavigationController, shown modally with presentation style 'formSheet'.
Unfortunately I was not able without modifying the source code to adjust the layout accordingly. The ImagePicker layout constraints and image gallery view are all set up assuming to be in fullscreen.

I think better would be not to use UIScreen.mainScreen.bounds as totalSize, but adjust the imagePicker according to the view size after the layout setup (e.g. in viewDidLayoutSubviews). 
This is the same for galleryView. An other thing is to use topLayoutGuide as topAnchor for Autolayout to make it possible to have a navigationBar.

**Comment by richardtop** [comment]
Related #269
