### ISSUE TITLE
How do i use this library for Objective-c ?

### ISSUE THREAD

**Issue by Smartmicros** [hyperoslo/ImagePicker#284]
![imagepicker error](https://cloud.githubusercontent.com/assets/2702863/24700724/7dcadfaa-1a11-11e7-8a83-c316ab92c702.png)
I installed via cocoapods in objective-c project , whenever i launch imagepicker its crashed.

**Comment by onmyway133** [comment]
@Smartmicros Hi, we don't officially support ObjC. But to workaround this, I think we need to implement `init(nibName:bundle:)` in `ImagePickerController`. You can try, and if better, make a PR 😉

**Comment by onmyway133** [comment]
@Smartmicros I think you solved it yourself 🍻

**Comment by windshadowlam** [comment]
May I know how to use in Objective C?
