### ISSUE TITLE
Sorting Issue

### ISSUE THREAD

**Issue by rajeevwhiz** [hyperoslo/ImagePicker#288]
Seems like there is a sorting issue with pictures. I am using the latest from Pod (shows as v2.1.1). It it possible to have a sorting option in configurations or sort in reverse chronological order by default?

**Comment by onmyway133** [comment]
@rajeevwhiz Hi, can you be more explicit on what "issue" you mean? Also, it would be great if you can submit a Pull request to solve this. We're looking forward to it

**Comment by rajeevwhiz** [comment]
On iPhone 7 running 10.3 I don't see this issue. On iPhone 6 running 10.1.1 the images are not sorted correctly... kind of random.

**Comment by musbaalbaki** [comment]
+1

**Comment by nCr78** [comment]
After restoring images from iCloud, the picker shows the first images I ever took with my past devices, not the latest ones. As a bonus, nothing happens when I pick them and press 'done' since they aren't actually downloaded on the device yet.
