### ISSUE TITLE
How to show tab bar 

### ISSUE THREAD

**Issue by ghost** [hyperoslo/ImagePicker#294]
Hello, thank you so much for sharing this wonderful project.
I'm new for developing iOS app, and I would like to use your project in my app. 
But I don't know how to adjust the layout with tab bar showing below. (Related #269)
Would be very appreciated if you could give some directions to how to adjust it. Thank you!

**Comment by richardtop** [comment]
Currently, there is no way to use it with the Tab Bar, please, see the related issue #282

**Comment by dearyuho** [comment]
I understand. Thank you so much.
