### ISSUE TITLE
Images.count doesn't match number of selected images

### ISSUE THREAD

**Issue by jpsanabria** [hyperoslo/ImagePicker#297]
I'm having a problem with this function

`func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage])`

`images.count ////doesn't return correct number of selected images`

The problem is inconsistent. I select 10 images. Sometimes it returns a count of 5, other times 7, one time it did just 3.

**Comment by jpsanabria** [comment]
I think it might be an issue with iCloud. It doesn't seem to load the images that are not on the device. I see that it is "fixed" in #262 but I do not understand how to implement the method to download the images

**Comment by jpsanabria** [comment]
Another updated. I added `requestOptions.isNetworkAccessAllowed = true` to AssetManage.swift. 

The issue now is that when the images are downloading, the screen looks a little static.

```
 open static func resolveAssets(_ assets: [PHAsset], size: CGSize = CGSize(width: 720, height: 1280)) -> [UIImage] {
    let imageManager = PHImageManager.default()
    let requestOptions = PHImageRequestOptions()
    requestOptions.isSynchronous = true
    requestOptions.isNetworkAccessAllowed = true


    var images = [UIImage]()
    for asset in assets {
      imageManager.requestImage(for: asset, targetSize: size, contentMode: .aspectFill, options: requestOptions) { image, info in
        if let image = image {
          images.append(image)
        }
      }
    }
    return images
  }
```

**Comment by madhavisolanki** [comment]
@jpsanabria were you able to solve this issue?

**Comment by madhavisolanki** [comment]
@jpsanabria I tried doing this in one of my file, it seems to work fine and I am able to download the image from cloud

```
  func getAssetThumbnail(asset: PHAsset, size:CGSize) -> UIImage? {
        let manager = PHImageManager.default()
        let option = PHImageRequestOptions()
        option.deliveryMode = .opportunistic
        option.isSynchronous = true
        option.resizeMode = .none
        option.isNetworkAccessAllowed = true
        var thumbnail = UIImage()
        manager.requestImage(for: asset, targetSize: size, contentMode: .aspectFit, options: option, resultHandler: {(result, info)->Void in
            if result == nil{
                thumbnail =  UIImage(named:"flower-27")!
            }else{
                thumbnail = result!
            }
        })
        return thumbnail
    }
```

But I am not able to get images from camera picker.

**Comment by mogis94** [comment]
hey guys, I am new to swift. I hope you guys can help me out. I am struggling to get the selected images from the customImagePicker to my ImageView. what is the right code for that? Thanks in Advance!!!
