### ISSUE TITLE
Image resolution issues

### ISSUE THREAD

**Issue by anhkhoi** [hyperoslo/ImagePicker#298]
I make a comparison:
1. I take a photo by camera app of iphone6s
Image resolution: 3024x4032

2. I open photo has captured above by ImagePicker
Image resolution: 2000x2668

Expected: image resolution isn't change.

Anything wrong here?

**Comment by anhkhoi** [comment]
I haved fixed my problem by set a specific preferredImageSize for image picker controller

**Comment by zenangst** [comment]
Hey @anhkhoi, glad you were able to solve the issue 👍
