### ISSUE TITLE
Messed up UI on iPad after orientation change

### ISSUE THREAD

**Issue by xxtesaxx** [hyperoslo/ImagePicker#301]
On iPad, depending on the orientation, the whole UI is more or less messed up. It depends on the orientation of the iPad when presenting the picker and then after rotating, it can get even worse.
![simulator screen shot 16 05 2017 20 54 48](https://cloud.githubusercontent.com/assets/3000808/26134122/5f1827a0-3a7a-11e7-879a-aa7333affd46.png)
![simulator screen shot 16 05 2017 20 54 51](https://cloud.githubusercontent.com/assets/3000808/26134119/5efda86c-3a7a-11e7-9604-c198d16ff385.png)
![simulator screen shot 16 05 2017 20 54 57](https://cloud.githubusercontent.com/assets/3000808/26134121/5eff707a-3a7a-11e7-9d41-6b0519849f26.png)
![simulator screen shot 16 05 2017 20 55 00](https://cloud.githubusercontent.com/assets/3000808/26134120/5efe5820-3a7a-11e7-80fa-2fec09d09261.png)
![simulator screen shot 16 05 2017 20 55 06](https://cloud.githubusercontent.com/assets/3000808/26134118/5efd5eac-3a7a-11e7-9344-d97c42f22a04.png)

**Comment by r-mckay** [comment]
Also experimenting this issue, on both iOS 9 and 10 versions of iPad Simulators.

**Comment by r-mckay** [comment]
It seems to work on iPad with "Requires full screen" at true.
@xxtesaxx, Does it solve your issue too?

<img width="390" alt="capture d ecran 2017-07-05 a 10 49 40" src="https://user-images.githubusercontent.com/3480946/27870086-e83a4e66-616f-11e7-8c63-17658633f29d.png">
