### ISSUE TITLE
open up setFlashButtonHidden

### ISSUE THREAD

**Issue by kohdesmond** [hyperoslo/ImagePicker#303]
Hi as above,

Possible to open up setFlashButtonHidden?

Cheers

**Comment by richardtop** [comment]
Hi @kohdesmond,
I'd like to clarify, do you need a method to completely disable flash button, or set it to some state on launch?

**Comment by kohdesmond** [comment]
Hi @richardtop completely disabled it.

Cheers!

**Comment by zenangst** [comment]
Closing this issue now.

**Comment by kohdesmond** [comment]
+1
