### ISSUE TITLE
Support for Swift 4 / Xcode 9

### ISSUE THREAD

**Issue by anushkmittal** [hyperoslo/ImagePicker#306]
The framework no longer compiles on Xcode 9 using Swift 4.

**Comment by HWSTS** [comment]
@anushkmittal  Have you find any solution ??

**Comment by huy-le** [comment]
@anushkmittal You can make a PR to solve that easily if you want to use Swift 4 now. In case of you use this framework as a library, it is compatible with Swift 3.2 of Xcode 9. So you are able to use it with your Swift 4 project on Xcode 9.

**Comment by ilyas91** [comment]
not working in xcode 9 beta 3 :(

**Comment by onmyway133** [comment]
@anushkmittal Like @huy-le said. We will support Swift 4 when it is officially release

**Comment by Shoshin23** [comment]
Hi! Is it supported on Xcode 9/Swift 4?

**Comment by sasquatchgit** [comment]
Swift 4 is officially released now.
