### ISSUE TITLE
No Camera Zoom Available

### ISSUE THREAD

**Issue by twhitt14** [hyperoslo/ImagePicker#308]
I would expect an image picker camera with this level of awesomeness to be able to zoom in when I "un-pinch" the live image, like in the regular camera app. Please add camera zoom :)

**Comment by zenangst** [comment]
Hey @twhitt14, you can try running the version that is on `master`. We recently merge https://github.com/hyperoslo/ImagePicker/pull/331 which should enable this kind of behavior.
