### ISSUE TITLE
Set selected images when opening second time?

### ISSUE THREAD

**Issue by JoniVR** [hyperoslo/ImagePicker#316]
Hi, 

FIrst of all, thankyou for this great Library, it really helps! 

I was wondering, is there a way to make the selected images highlighted if the user opens the `ImagePicker` for a second time? 
I looked through the issues and didn't find a solution (as far as I could tell)

_For example:_
User opens the `ImagePicker`, picks 3 photo's, presses "done" and then decides he wants to add/remove a photo, is it possible to open the `ImagePicker` with the already selected photo's highlighted? 

Thanks in advance!

**Comment by murad1981** [comment]
I'm facing the same issue, is there a way to show the previously selected assets ?

**Comment by mmorey** [comment]
If you don't dealloc your instance of the ImagePickerController, by keeping a strong reference to it in your presenting view controller, it will keep and show your previous selection of images no matter how many times you present it.

**Comment by JoniVR** [comment]
Thanks for that @mmorey, I'll try it out when I get the time!

**Comment by JoniVR** [comment]
@mmorey This worked, stupid that I didn't think of this! Thanks a lot!
