### ISSUE TITLE
iPad landscape

### ISSUE THREAD

**Issue by AmirDaliri** [hyperoslo/ImagePicker#319]
HI
imagePicker crashed on iPad landscape, 
how to fix it?

**Comment by pmcavoy89** [comment]
I'm seeing the same issue here. I'm on iOS 10 using Swift 3.

**Comment by pmcavoy89** [comment]
I would like to know if the project maintainers would like a PR from me to re-enable this? I'd be happy to do so otherwise I'll keep a fork.
