### ISSUE TITLE
dumb question: demo images location?

### ISSUE THREAD

**Issue by wdcurry** [hyperoslo/ImagePicker#320]
I am sure the coffee is not yet kicking in, but where the heck are the images presented in the demo, and in the simulator? They are seemingly hi-res, which creates a long delay in demo'ing certain features that are online-related. I want to swap them out but cannot find them.

**Comment by annjawn** [comment]
What do you mean by the "images presented in the demo"? If you are using simulator then the image picker will pull in the simulators default camera roll which usually has a few stock images. If you are using your physical device then your device's camera roll will be shown in the image picker.

**Comment by onmyway133** [comment]
@annjawn Thanks for the answer
