### ISSUE TITLE
Poor low-light images and Cocoapods installed version issue

### ISSUE THREAD

**Issue by annjawn** [hyperoslo/ImagePicker#321]
The low light images are too poor in comparison to the stock camera app and almost always requires flash.

Also, the version installed through cocoapods seem to be a slightly different version than is used in the sample project. for example in the version installed through cocoapods the `Configuration()` options listed below are missing-

  ```
public var allowVideoSelection = false
  public var showsImageCountLabel = true
  public var flashButtonAlwaysHidden = false
  public var managesAudioSession = true
```

**Comment by richardtop** [comment]
Hi @annjawn,
I cannot comment on the first part of your question, but I'll explain about the second.
When new features get merged into master, they're not immediately published (via Release), rather aggregated and then published as a new version of the pod.
Therefore, what gets downloaded is not the current head of the master branch, but the latest release.

To always download the latest commit from the master branch, specify in your `podfile`:
`pod 'ImagePicker',  :git => 'https://github.com/hyperoslo/ImagePicker.git'`
Cocoapods takes the latest commit from the default branch (`master` in this case) with all the relevant changes and new features.

**Comment by onmyway133** [comment]
@annjawn Hi, sorry for late response. You can check https://github.com/hyperoslo/ImagePicker/releases/tag/3.0.0
