### ISSUE TITLE
No Such module 'Gallery'

### ISSUE THREAD

**Issue by ghousenaren** [hyperoslo/ImagePicker#322]
using pods

searched solutions for the above issue in StackOverflow, but no helped out

**Comment by zenangst** [comment]
Hey @ghousenaren, could you share some more information about your setup?
What does your Podfile look like?

**Comment by onmyway133** [comment]
@ghousenaren Hi, you may mistake this with some other pod. This names `ImagePicker` 😉 . Close for lack of activity
