### ISSUE TITLE
CancelButtonDidPress dissmiss viewController

### ISSUE THREAD

**Issue by karpov3** [hyperoslo/ImagePicker#323]
Hi, thank you for ImagePicker.
I notices that function "cancelButtonDidPress" in ImagePickerController calls dismiss(animated: true, completion: nil). May be this method should call only delegate method "delegate?.cancelButtonDidPress(self)". I use navigationController and dismiss method hide my parent viewController.
Thank you
karpov3

**Comment by zenangst** [comment]
Hey @karpov3, we could totally make that happen. If you make a PR for this we would gladly review it :)

**Comment by onmyway133** [comment]
@karpov3 Hi, we fixed this for you during the swift 4 migration. Now you can just dismiss in your delegate method https://github.com/hyperoslo/ImagePicker/pull/345
