### ISSUE TITLE
let the rest of images become gray when it's up to limit

### ISSUE THREAD

**Issue by Lec2cn** [hyperoslo/ImagePicker#332]
let the rest of images become gray when it's up to limit

![image](https://user-images.githubusercontent.com/3175144/29762871-3c8c3534-8c03-11e7-8138-ceb619b62de0.png)

When the user select the max of the limit of images (limit: 3) , the rest of images that user didn't select , can u make them become  RGBA(0,0,0,0.5).

Thx.

**Comment by zenangst** [comment]
hey @Lec2cn, could you go into a little bit more depth into what you are trying to achieve ?

**Comment by Lec2cn** [comment]
hey @zenangst  , i update an picture that shows what i'm trying to achieve. Please check for the updates.thx

**Comment by zenangst** [comment]
Aha, so when the limit is reached you want a clear indicator that they are disabled. We are not currently adding new features to `ImagePicker` but feel free to make a PR adding this feature if you like and we will gladly review it 😎

**Comment by Lec2cn** [comment]
@zenangst  OK. 😎
