### ISSUE TITLE
Video selection

### ISSUE THREAD

**Issue by damienissa** [hyperoslo/ImagePicker#334]
You have merged issue #283 to your master branch. But you have no changes at your CocoaPods library. Please check it.

**Comment by richardtop** [comment]
Hi @damienissa, 
new versions are released eventually, until now, you can point CocoaPods to use the master branch of this repository:
```Ruby
pod 'TSMessages',  :git => 'https://github.com/hyperoslo/ImagePicker.git, :branch => 'master'
```
Or, specify `swift4` branch if you've already migrated.

**Comment by onmyway133** [comment]
@damienissa Hi, as @richardtop said. You can also checkout 3.0.0 https://github.com/hyperoslo/ImagePicker/releases/tag/3.0.0
