### ISSUE TITLE
Could we have swift 4 branch at least?

### ISSUE THREAD

**Issue by pluckq** [hyperoslo/ImagePicker#337]
xcode GM already exist.

**Comment by zenangst** [comment]
Hey @pluckq, yeah Apple just recently released the GM which is fantastic and we do plan to update all our frameworks to support this. However, we have a lot of frameworks so this will be a time consuming effort on our part. We plan to do it in the near future but to not stress out completely we will take one framework at a time starting with our core foundation frameworks such as `Cache`, `Sugar` etc.

If anyone in the community wants to help out making this migration then we are all for it!
Hope you understand, all the best!

**Comment by zenangst** [comment]
Oh, minor update... we already have a PR with a swift 4 migration going on.
https://github.com/hyperoslo/ImagePicker/pull/335

I've created a `swift4` branch on the repo now and asked the author of the PR to point to that branch instead.

**Comment by annjawn** [comment]
I am facing all kinds of errors with the swift4 branch.

<img width="1420" alt="screen shot 2017-10-04 at 12 51 17 am" src="https://user-images.githubusercontent.com/26977294/31165013-325f1614-a89e-11e7-8e8c-ca0362dc4b8c.png">

**Comment by onmyway133** [comment]
@pluckq Hi, you can check version 3.0.0 https://github.com/hyperoslo/ImagePicker/releases/tag/3.0.0
@annjawn Hi, please make sure you set swift version in your project to 4.0. Please check demo project to see if you still get the problems
