### ISSUE TITLE
Strange logs

### ISSUE THREAD

**Issue by vadimvitvickiy** [hyperoslo/ImagePicker#340]
Hello, I'm facing some issue in console:
[ImageManager] Unable to load image data, /var/mobile/Media/DCIM/100APPLE/IMG_0042.JPG
But still can get images and assets

**Comment by onmyway133** [comment]
@pluckq Hi, we haven't had this problem. Did you use simulator? If you reset and clear cache data on simulator, does this problem still exists?

**Comment by edwinfinch** [comment]
Hey there, I'm having a similar issue on iOS 11. I reinstalled my app from scratch and after allowing both photo permissions again, trying to tap "Done" after selecting a photo results in:

`[ImageManager] Unable to load image data, /var/mobile/Media/DCIM/118APPLE/IMG_8015.HEIC`

I want to note I'm using the library on Objective-C, so you may consider my report invalid, though I figured I'd let you know anyway.

**Comment by robindirksen1** [comment]
@edwinfinch I have the same with ios 11 (swift 3)

**Comment by justinackermann** [comment]
I am also having this issue as well on a physical iPhone 8 using swift. Both with photo library and images taken with the camera.
