### ISSUE TITLE
Make swift4 branch master

### ISSUE THREAD

**Issue by richardtop** [hyperoslo/ImagePicker#344]
Given Swift4 is now mainstream, its a good idea to make `swift4` a default branch. Those, who not migrated could use a `swift3` version.

**Comment by DavidKababyan** [comment]
how can i use swift 4 branch? in pods im getting swift 3 version.
i want to add swift 4 brach to my project.

**Comment by richardtop** [comment]
@DavidKababyan check out this guide:
https://stackoverflow.com/questions/39930664/how-to-install-a-pod-from-a-specific-branch

**Comment by onmyway133** [comment]
@richardtop thanks, swift4 branch has been merged to master now
