### ISSUE TITLE
Facing issues in Swift 4

### ISSUE THREAD

**Issue by harshit-mapmyindia** [hyperoslo/ImagePicker#346]
hi,
I am facing compatibility issues with xcode 9 , some syntax needs to be updated

**Comment by onmyway133** [comment]
@harshit-mapmyindia Hi, can you show us the screenshot? Also, did you update swift version to 4.0 in your project settings?

**Comment by harshit-mapmyindia** [comment]
no im still on swift 3.2 but i reinstalled the pod after that im getting this issue 
<img width="655" alt="screen shot 2017-10-10 at 2 37 21 pm" src="https://user-images.githubusercontent.com/32668977/31378363-a07147d8-adc8-11e7-8f91-20a0b20b8025.png">
<img width="778" alt="screen shot 2017-10-10 at 2 37 28 pm" src="https://user-images.githubusercontent.com/32668977/31378364-a0a6d3e4-adc8-11e7-946d-039697c68ce4.png">
<img width="1013" alt="screen shot 2017-10-10 at 2 37 39 pm" src="https://user-images.githubusercontent.com/32668977/31378366-a0d6e354-adc8-11e7-9262-b323d216a1bf.png">

**Comment by onmyway133** [comment]
If you use https://github.com/hyperoslo/ImagePicker/releases/tag/3.0.0, you should update your project to swift 4

**Comment by DavidKababyan** [comment]
when i download with pods i get 2.1.1 version doesnt work with xcode 9.
new project on xcode 9. no code at all. installed pod ab build. 26 errors.

**Comment by rajeevwhiz** [comment]
Getting following errors -- both from Pod (3.0.0) or directly from Git

```Pods/ImagePicker/Source/Configuration.swift:17:70: Type 'UIFont' has no member 'Weight'
Pods/UIKit.UIFont:46:14: Did you mean 'xHeight'?
Pods/ImagePicker/Source/Configuration.swift:18:65: Type 'UIFont' has no member 'Weight'
Pods/UIKit.UIFont:46:14: Did you mean 'xHeight'?
Pods/ImagePicker/Source/Configuration.swift:19:66: Type 'UIFont' has no member 'Weight'
Pods/UIKit.UIFont:46:14: Did you mean 'xHeight'?
Pods/ImagePicker/Source/Configuration.swift:20:67: Type 'UIFont' has no member 'Weight'
Pods/UIKit.UIFont:46:14: Did you mean 'xHeight'?
Pods/ImagePicker/Source/Configuration.swift:21:67: Type 'UIFont' has no member 'Weight'
Pods/UIKit.UIFont:46:14: Did you mean 'xHeight'?
Pods/ImagePicker/Source/Configuration.swift:22:67: Type 'UIFont' has no member 'Weight'
Pods/UIKit.UIFont:46:14: Did you mean 'xHeight'?

Pods/ImagePicker/Source/CameraView/CameraMan.swift:38:14: Value of type 'Any' has no member 'hasMediaType'
Pods/ImagePicker/Source/CameraView/CameraMan.swift:38:14: Cast 'Any' to 'AnyObject' or use 'as!' to force downcast to a more specific type to access members

Pods/ImagePicker/Source/CameraView/CameraMan.swift:70:53: Incorrect argument label in call (have 'for:', expected 'forMediaType:')
Pods/ImagePicker/Source/CameraView/CameraMan.swift:83:34: Incorrect argument label in call (have 'for:_:', expected 'forMediaType:completionHandler:')
Pods/ImagePicker/Source/CameraView/CameraMan.swift:153:56: Incorrect argument label in call (have 'with:', expected 'withMediaType:')

Pods/ImagePicker/Source/CameraView/CameraMan.swift:236:45: Argument labels '(rawValue:)' do not match any available overloads
Pods/ImagePicker/Source/CameraView/CameraMan.swift:236:45: Overloads for 'AVCaptureSession.Preset' exist with these partially matching parameter lists: (coder: NSCoder), (stringLiteral: StaticString), (format: NSString, CVarArg...), (string: NSString), (utf8String: UnsafePointer<Int8>), (UTF8String: UnsafePointer<Int8>), (string: String), (contentsOfFile: String), (contentsOf: URL), (contentsOfURL: URL), (cString: UnsafePointer<Int8>), (CString: UnsafePointer<Int8>)

Pods/ImagePicker/Source/CameraView/CameraMan.swift:237:38: Argument labels '(rawValue:)' do not match any available overloads
Pods/ImagePicker/Source/CameraView/CameraMan.swift:237:38: Overloads for 'AVCaptureSession.Preset' exist with these partially matching parameter lists: (coder: NSCoder), (stringLiteral: StaticString), (format: NSString, CVarArg...), (string: NSString), (utf8String: UnsafePointer<Int8>), (UTF8String: UnsafePointer<Int8>), (string: String), (contentsOfFile: String), (contentsOf: URL), (contentsOfURL: URL), (cString: UnsafePointer<Int8>), (CString: UnsafePointer<Int8>)

Pods/ImagePicker/Source/CameraView/CameraMan.swift:245:7: Type 'AVCaptureSession.Preset' (aka 'NSString') has no member 'high'```

**Comment by rajeevwhiz** [comment]
Swift4 branch (showing as version 2.1.1) -- same issue.

**Comment by rajeevwhiz** [comment]
User error -- Ignore. Had to manually update Swift compiler settings for the Pod

**Comment by onmyway133** [comment]
@rajeevwhiz Hi, how do you know you're using Swift 4? Have you set swift version to 4.0 in your build settings ?

**Comment by DavidKababyan** [comment]
usually xcode 9 starts by default on swift 4. Now the pods were updated and im getting imagePicker version 3.0.0 and works fine, no errors so far!

**Comment by AlbertoLourenco** [comment]
I'm using Swift 4 with lib version 3.0.0 and getting many errors. :(

**Comment by iOSUser110** [comment]
I am laso getting error on xcode 9 for swift 4 also and for swift 3.2 also,
on both version 3.0.0 and 2.1.1   , facing issues,  :(

**Comment by NinoScript** [comment]
For people who are having problems with this and are using cocoapods, try `pod deintegrate` before `pod install`. In my case  that'll force it to regenerate the project files, and update `SWIFT_VERSION` to the correct number. At least that helped **me**.

**Comment by rafipiccolo** [comment]
thanks for the advice, I had to change swift language version in each package of the project...
xcode is shit af

**Comment by onmyway133** [comment]
@iOSUser110 @AlbertoLourenco @DavidKababyan @rajeevwhiz Can you try do `pod deintegrate` and `pod install` as @NinoScript pointed out and see if it works for you ?

**Comment by allanpichardo** [comment]
What worked for me was going into the Pods project settings > ImagePicker target > Build Settings > Swift language version > Selecting Swift 4.0 then rebuild

**Comment by prasads** [comment]
image picker not giving selected photos?

**Comment by gisngocthach** [comment]
Set the SWIFT_VERSION to 4 in the Podfile and then try to do pod deintegrate and pod install
