### ISSUE TITLE
Warn some lines

### ISSUE THREAD

**Issue by janibekm** [hyperoslo/ImagePicker#349]
I was installed imagepicker by pod!
i got two more line warnings
setStatusBarHidden(_:with:)' was deprecated in iOS 9.0: Use -[UIViewController prefersStatusBarHidden]

Question!
how to record video, like taking photo ?

thank you!

**Comment by jpm-polymorph** [comment]
I'm busy porting our codebase to Swift 4, and in the process I'm cleaning up warnings where I can. I am also encountering this warning with ImagePicker:
`'setStatusBarHidden(_:with:)' was deprecated in iOS 9.0: Use -[UIViewController prefersStatusBarHidden]`

It appears in `ImagePickerController.swift` lines 133 and 160.

The severity is low, but it would be nice fixing this.
