### ISSUE TITLE
Done button unresponsive

### ISSUE THREAD

**Issue by ninoid** [hyperoslo/ImagePicker#353]
Users report they cannot click “Gedaan” Dutch (translates to: “Done”) when they are selecting image. Report came from IPhone 6. iPhone is set on Dutch language
But the button is present on the screen
Just nothing happens when you tap it

**Comment by zenangst** [comment]
Hey @ninoid,

Have you hooked up your handler to the `ImagePickerDelegate` and added a method for handling the `Done` invocations? (https://github.com/hyperoslo/ImagePicker/blob/master/Source/ImagePickerController.swift#L8)

**Comment by ninoid** [comment]
Yes, of corse. But there is guard statement start of block

print("Finish button pressed.")

guard let image = images.first else { return }

....


Selection mode is single image. I mean there is only posssible to select
one image. BTW done button can not be visibile if there is no images
selected. only cancel button title is visible in that case.

**Comment by egenvall** [comment]
I recently received a similar report:
- Single Image
- iPhone 6S running iOS 11.1

Saving an image when taken with camera works, but not when selected from library.

Can not reproduce the issue on iPhone 7+ iOS  11.1
