### ISSUE TITLE
Video get asset

### ISSUE THREAD

**Issue by leobouilloux** [hyperoslo/ImagePicker#354]
Hello,

I was wondering how to get my video as data after selecting it:

```swift
    func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
        imagePicker.dismiss(animated: true)
    }
```

Thank you very much,

**Comment by chimura** [comment]
Have you find any solution for that?

**Comment by leobouilloux** [comment]
Hello @chimura , I'm now using [Gallery](https://github.com/hyperoslo/Gallery) to fit my needs.

Hope it helps :)
