### ISSUE TITLE
Not working in Objective-C / Appcelerator Hyperloop

### ISSUE THREAD

**Issue by hansemannn** [hyperoslo/ImagePicker#357]
Hey guys,

we are currently trying to expose this great library as a sample for using Swift 4 pods in [Appcelerator Hyperloop](http://www.appcelerator.com/mobile-app-development-products/hyperloop/) / Titanium. 

Unfortunately, the app crashes after calling the default initializer, because we use generated Obj-C headers for the import (e.g. `#import <ImagePicker/ImagePicker-Swift.h>`. This happens because of https://github.com/hyperoslo/ImagePicker/issues/284 and has popped up again. It could likely being fixed by expose the classes and initializer to Obj-C, not sure what the roadmap there is to support those projects as well.

Anyway, thanks for this library!

**Comment by zenangst** [comment]
Hey @hansemannn, we don't intend to support Objective-C for this library, and by that I mean that we don't intend to make it. With that said, I'd gladly review a PR if someone were make this fix :)

**Comment by zenangst** [comment]
@hansemannn I just merged your PR so I think we can close this issue now :)
Will you publish the sample anywhere?

**Comment by hansemannn** [comment]
Thank you @zenangst, will do over the next 1-2 weeks 🙏.

**Comment by hansemannn** [comment]
@zenangst So I've done a sample and it works. But the `Lightbox` library also does not properly support Obj-C, so we would need to migrate that one as well.

**Comment by jonasfunk** [comment]
@hansemannn, would you mind sharing the sample you've done in Hyperloop? Been trying to expose `ImagePicker` (without the `Lightbox` library), but with no success.

**Comment by Matt-Marsland** [comment]
@hansemannn did you ever manage to get this working with Hyperloop? I have been wanting to use this image picker in an Appcelerator project for ages, but I didn't have any luck.
