### ISSUE TITLE
canRotateCamera not working

### ISSUE THREAD

**Issue by niloupharAV** [hyperoslo/ImagePicker#363]
when I use canRotateCamera = true it's not workimng and camera still is in portrait mode

**Comment by tomasbykowski** [comment]
Try changing it directly in the in the source file "Configurations".

**Comment by 350541732** [comment]
@tomasbykowski   i faced this canRotateCamera not working....i see in the   "Configurations"
'public var canRotateCamera = true'  can u  tell me how to resolve it ?

**Comment by 350541732** [comment]
@niloupharAV  did u resolve it ?
