### ISSUE TITLE
'doneButtonDidPress' not returning images

### ISSUE THREAD

**Issue by pravishanth** [hyperoslo/ImagePicker#368]
Hi,

After images are picked the delegate method, 'func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage])' is not returning images. images.count is returning zero

imagePicker pod version: 2.1.1
Deployed on iOS 10.0 (iPhone 5)

**Comment by jhonyourangel** [comment]
i get only one image in the array. Why ?

**Comment by ZeroFengLee** [comment]
I got the same problem

**Comment by jhonyourangel** [comment]
You need to set :
```
settings = {
    // external mode expect the data to be refetch from the server
mode: 'inline',
    delete: {
      confirmDelete: true,
    },
    add: {
      confirmCreate: true,
    },
    edit: {
      confirmSave: true,
    }
}
```

Or just 

`settings: {mode:external}` 

And it will work

**Comment by DerekYuYi** [comment]
You can set value of `preferredImageSize` property to not nil, for example:
 
```Swift
 imagePicker.preferredImageSize = CGSize(width: 120, height: 120)
```

and it works.
