### ISSUE TITLE
how to retrieve selected images from imagePicker to my ImageView in ViewController?

### ISSUE THREAD

**Issue by mogis94** [hyperoslo/ImagePicker#376]
Hey everyone! I'm new to swift. What is the right code to get the selected images from ImagePicker to my ImageView? I hope you can help me out!

Basically, I've just installed the custom ImagePickerController from https://github.com/hyperoslo/ImagePicker. So my question is how do you get the selected images from the custom Image Picker to my ImageView. Ive implemented everything that was mentioned on the website. Let me show you what I've got so far:

import Foundation
import UIKit
import ImagePicker

var imagePicker = ImagePickerController()

public var imageAssets: [UIImage] {
    return AssetManager.resolveAssets(imagePicker.stack.assets)
}

class ViewController: UIViewController, UINavigationControllerDelegate, ImagePickerDelegate {
    
    @IBOutlet weak var image: UIImageView!
 
    override func viewDidLoad() {
        imagePicker.delegate = self
    }
    
    @IBAction func uploadPic(_ sender: UIButton) {
        
    //sender.isHidden = true
        
        let imagePicker = ImagePickerController()
        imagePicker.delegate = self
        present(imagePicker, animated: true, completion: nil)
    }
    
    func wrapperDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
    
    }
    
    func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
        
        let images = imageAssets
        
        self.image.image = images
        
        imagePicker.dismiss(animated: true, completion: nil)
    }

THANKS IN ADVANCE!

**Comment by jhonyourangel** [comment]
```func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
    
   // let images = imageAssets
    
// images is he return from the delegate
    self.image.image = images[0]
    
    imagePicker.dismiss(animated: true, completion: nil)
}```
