### ISSUE TITLE
can i capture video ?

### ISSUE THREAD

**Issue by jhonyourangel** [hyperoslo/ImagePicker#380]
can it capture video ?

**Comment by zenangst** [comment]
Hey @jhonyourangel, when we built `ImagePicker` we focused on snapping pictures and not video. However, if you want a framework that supports both then we encourage you to check out http://github.com/hyperoslo/Gallery, it has support for both images and video.

**Comment by jhonyourangel** [comment]
thank you, but we made our own. our is like whatsup:
selects images and video
capture photo and video
we will publish it later next week on cocoapod

**Comment by zenangst** [comment]
@jhonyourangel that's awesome! looking forward to checking it out.

**Comment by rsekar1094** [comment]
Hi @jhonyourangel ,is your fork ready for capturing video?

**Comment by jhonyourangel** [comment]
Have a look at this repository
https://github.com/jhonyourangel/ImagePickerWhatsApp <https://github.com/jhonyourangel/ImagePickerWhatsApp>

I have troubles posting it on cocoa pod, but it works directly from the GitHub


Please let me know if you need any help implementing it

**Comment by rajendersha** [comment]
interested in capturing video section.
