### ISSUE TITLE
Transparent BottomContainer like WhatsApp

### ISSUE THREAD

**Issue by alexanderkorus** [hyperoslo/ImagePicker#381]
Hello,
could anyone help me?
I forked the project, because I want to make the BottomContainer transparent, like in WhatsApp. Now I am struggling to edit the GalleryCollectionView so, that wenn I collapse it, it doesn't be behind the CameraView. First I'm trying to make the GalleryView invisible, when I collapse it, but in the "slide down" Flow, it will not be perfect. Then I wanted to make the BottomContainer, replicate from the CameraView PreviewLayer, but this doesn't work too. Do anyone have an Idea, how I can realize this? Here ist a Screenshot from whatsApp, what I try to achieve:
![alt](https://image.ibb.co/fxRtKR/IMG_0688.jpg)

**Comment by richardtop** [comment]
Hi, @BigAlKo,
here is what I've achieved by quickly tweaking the library:
![img_0553](https://user-images.githubusercontent.com/8013017/35771593-10cc6a9c-0938-11e8-8649-0a547686f482.PNG)
The recipe is as follows:
1. Set background color of the elements you want to be transparent to `.clear`
2. Add a bit of padding to `GalleryView`'s cells
3. Change layout constraints of `CameraView`:
Remove this:
```Swift
    view.addConstraint(NSLayoutConstraint(item: cameraController.view, attribute: .height,
      relatedBy: .equal, toItem: view, attribute: .height,
      multiplier: 1, constant: -BottomContainerView.Dimensions.height))
```

And add `.bottom` here:
```Swift
    for attribute: NSLayoutAttribute in [.left, .top, .width, .bottom] {
      view.addConstraint(NSLayoutConstraint(item: cameraController.view, attribute: attribute,
        relatedBy: .equal, toItem: view, attribute: attribute,
        multiplier: 1, constant: 0))
    }
```
in `ConstraintsSetup` file.

This should be pretty close to the effect you are trying to achieve.

**Comment by BigAlKo** [comment]
Thank you very much. So simple and I try so many complex things 🤷🏼‍♂️🤗

**Comment by richardtop** [comment]
@BigAlKo feel free to close this issue then.
