### ISSUE TITLE
iCloud Photo Problem

### ISSUE THREAD

**Issue by aakpro** [hyperoslo/ImagePicker#382]
When user iCloud photo is on, if image picker choose a photo with source type = typeCloudShared, there will be no image value. It happens in here [AssetManager#54](https://github.com/hyperoslo/ImagePicker/blob/ce33e9bc61b59924c0051fd0abb3f16d514594b3/Source/AssetManager.swift#L54). When it is called from here [ImagePickerViewController#370](https://github.com/hyperoslo/ImagePicker/blob/ce33e9bc61b59924c0051fd0abb3f16d514594b3/Source/ImagePickerController.swift#L370)

I believe this line of code should be added:
`    requestOptions.isNetworkAccessAllowed = true
`

**Comment by Azureheal** [comment]
I had the same issue.  None of my simulator's images are stored on iCloud and it works fine; however, my iPhone has all my images stored on iCloud and it does not work.
