### ISSUE TITLE
Optional Camera/Library view only

### ISSUE THREAD

**Issue by arvidurs** [hyperoslo/ImagePicker#384]
Not sure if the title makes entirely sense, 
but I think it would be a great addition to just be able to present the imagepicker in photo mode or library mode alone. Which would mean the library would be full screen.

**Comment by choujar** [comment]
I'd live this too!

**Comment by Daxito** [comment]
+1

**Comment by hakanstegborn** [comment]
+1

**Comment by qaavi** [comment]
+1

**Comment by rjalkuino** [comment]
+1

**Comment by thesanjaythakkar** [comment]
+1

**Comment by frknbyhn** [comment]
+1
