### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by appfactoryCo** [hyperoslo/ImagePicker#386]
I get 13 Swift compiler errors. Some of the errors are:

> /ImagePicker/Source/Configuration.swift:18:65: Type 'UIFont' has no member 'Weight'

> /ImagePicker/Source/CameraView/CameraMan.swift:153:56: Incorrect argument label in call (have 'with:', expected 'withMediaType:')

> /ImagePicker/Source/CameraView/CameraMan.swift:236:45: Argument labels '(rawValue:)' do not match any available overloads

Is there something I need to do to resolve the compiler errors? I'm using Swift 4 in Xcode 9.2

**Comment by dhirenthirani** [comment]
I am facing the same issue. 
Can anyone pls help?

**Comment by mabdullahsaeed** [comment]
Same issue, can anyone please update?

**Comment by CanTheAlmighty** [comment]
I had this exact same problem, but realized that I was overriding the Swift version when installing the pods to swift 3:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' # <-- Change to 4.0 or 4.1
    end
  end
end
```

**Comment by obadasemary** [comment]
How To fix this issue?
Can anyone pls help?
