### ISSUE TITLE
doneButtonDidPress returns only 1 images

### ISSUE THREAD

**Issue by Neeraj204** [hyperoslo/ImagePicker#387]
It was working really good before but suddenly it stopped working the way it was.
When I Click camera photo and selects more other pics from gallery, it only returns first image selected.

Below is the code for opening:

`var config = Configuration()
                config.doneButtonTitle = "Finish"
                config.noImagesTitle = "Sorry! There are no images here!"
                config.recordLocation = false
                //config.allowVideoSelection = true
                
                let imagePicker = ImagePickerController(configuration: config)
                imagePicker.delegate = self
                imagePicker.imageLimit = 5 - self.profileImages.count
                present(imagePicker, animated: true, completion: nil)`

and code for Done button:

`func doneButtonDidPress(_ imagePicker: ImagePickerController, images: [UIImage]) {
        selectedImages = images
        imagePicker.dismiss(animated: true, completion: nil)
        for image in images {
            self.profileImages.append(image)
        }
        
        if self.profileImages.count > 0 {
            self.bottomViewBConstraint.constant = 0
        }
        self.profileCollectionView.reloadData()
        //        appDelegate.imagesArray = [["images": selectedImages as AnyObject]]
        //        print(appDelegate.imagesArray)
    }`

This issue happens sometimes, please check and revert ASAP.

**Comment by aksswami** [comment]
@Neeraj204 you are using `imagePicker.imageLimit = 5 - self.profileImages.count`. Please check what is the `profileImages.count` is returning when you have this issue. 

You are getting one image because of this constraint.

**Comment by Neeraj204** [comment]
Thanks for your reply. `profileImages.count` is my array which contains previously selected images and it returns 2. It is not related to that array, even if I don't use limit it also returns 1.
