### ISSUE TITLE
Wrong sorting for Images

### ISSUE THREAD

**Issue by yehiabairm** [hyperoslo/ImagePicker#390]
When i open Picker for first time, I got images from old to new, oldest first, if i close picker and opened it again, i got newest pic again, how to get the newest by default!

**Comment by ambarakat** [comment]
I have the same problem 

I debug all code and not catch the problem

**Comment by sbintl** [comment]
Same issue with me any solution?

**Comment by 3lvis** [comment]
Hi @sbintl, this project is in maintenance mode, no new work other than updating Xcode and the latest version of Swift will be done. If you want to submit a fix for the problem I'll be happy to review it and merge it.

**Comment by faizannaseem96** [comment]
Same issue with me any solution?
