### ISSUE TITLE
Unable to load image data

### ISSUE THREAD

**Issue by abbana** [hyperoslo/ImagePicker#392]
Hi,

iphone7, iOS 11.2.6.

With both iCloud and non iCloud images (deactivated) I got

outputDeviceDiscoverySessionDidChangeDiscoveryMode:]: Setting device discovery mode to DiscoveryMode_Presence (client: xxx)
2018-02-25 23:09:41.483388+0000 Regional2[1203:184162] [ImageManager] Unable to load image data, /var/mobile/Media/DCIM/100APPLE/IMG_0094.HEIC

Tried adding the below in AssetManager

        requestOptions.deliveryMode = .highQualityFormat
        requestOptions.isNetworkAccessAllowed = true
        requestOptions.isSynchronous = true
        requestOptions.resizeMode = .exact

No luck.

Anyone able to solve this issue?

This could be duplicate of iCloud issue, but applying those workarounds didn't solved the issue in my case.

**Comment by KBvsMJ** [comment]
# @abbana
