### ISSUE TITLE
exif information lost in the photo

### ISSUE THREAD

**Issue by memetea** [hyperoslo/ImagePicker#396]
ImagePicker convert the jpeg represent data to UIImage and then return it to application.  the exif information lost in such transfer.   return the exif is better because application may use it.

**Comment by sedwo** [comment]
@memetea Try this:  https://github.com/sedwo/ImagePicker

**Comment by wsbuser** [comment]
I tried using the https://github.com/sedwo/ImagePicker , but imageFileURL are all nil. What am I doing wrong?

**Comment by sedwo** [comment]
```
    func showImagePickerAction() {
        let config = Configuration()
        config.savePhotosToCameraRoll = false
        config.exifUserComment = appNameVersionAndBuildDateString() // As an fyi: tag new photos with app build string.

        let imagePicker = ImagePickerController(configuration: config)
        imagePicker.delegate = self
        ImagePickerController.photoQuality = AVCaptureSession.Preset.photo  // full resolution photo quality output

        present(imagePicker, animated: true, completion: nil)
    }

```

**Comment by wsbuser** [comment]
I am still getting nil for images.first?.imageFileURL in doneButtonDidPress function.

**Comment by wsbuser** [comment]
Any Idea why imageFileURL is returning nil ?, or anything I need to change to get the file path.
