### ISSUE TITLE
Unable to load image data, /var/mobile/Media/DCIM/101APPLE/<imgName>.JPG

### ISSUE THREAD

**Issue by antonijap** [hyperoslo/ImagePicker#397]
I am using the latest version and when I call done delegate method my console fills with
`Unable to load image data, /var/mobile/Media/DCIM/101APPLE/<imgName>.JPG`
What could it be?

**Comment by antonijap** [comment]
I thought it went away. Nope, still in console.

**Comment by 0x0w1** [comment]
Same problem, it seems like a bug with iOS 11

**Comment by sheharyar-rr** [comment]
Having the same issue. Optimise iPhone Storage option for Photos app has been turned on, which may be the root cause.

**Comment by KBvsMJ** [comment]
@antonijap   try this：
AssetManager.swift:

` open static func resolveAssets(_ assets: [PHAsset], size: CGSize = CGSize(width: 720, height: 1280)) -> [UIImage] {
    let imageManager = PHImageManager.default()
    let requestOptions = PHImageRequestOptions()
    requestOptions.isSynchronous = true
    requestOptions.deliveryMode = .highQualityFormat
    requestOptions.isNetworkAccessAllowed = true
    requestOptions.resizeMode = .exact
    var images = [UIImage]()
    
    for asset in assets {
    
      imageManager.requestImage(for: asset, targetSize: size, contentMode: .aspectFill, options: requestOptions) { image, _ in
     
        if let image = image {
          images.append(image)
        }
      }
    }
    return images
  }
}`

**Comment by kishykumar** [comment]
Hitting the same issue. Please fix.

**Comment by hixfield** [comment]
@KBvsMJ could you explain your proposal in more detail?

**Comment by jack45j** [comment]
Same issue here and still not work after replaced the code in resolveAssets function.
