### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by edwardmp** [hyperoslo/ImagePicker#419]
Hi maintainers,

Can you release a new version? There's been some stuff fixed since the last release!

**Comment by edwardmp** [comment]
CC @RamonGilabert

**Comment by edwardmp** [comment]
@vadymmarkov can you please look into this? Thanks!

**Comment by vadymmarkov** [comment]
@edwardmp Version 3.1.0 is out now https://github.com/hyperoslo/ImagePicker/releases/tag/3.1.0

**Comment by edwardmp** [comment]
@vadymmarkov awesome! thanks so much
