### ISSUE TITLE
Is it possiable for show only Gallery Content not camera section???

### ISSUE THREAD

**Issue by KaranMehta3984** [hyperoslo/ImagePicker#422]

**Comment by SirWellington** [comment]
I have the same question

**Comment by vinothvino42** [comment]
Yeah, please give any properties to make only gallery to show in full screen.

**Comment by vikassingh-kiwi** [comment]
please give any properties to make the only a gallery to show in full screen.

**Comment by 3lvis** [comment]
Hi! If you make a PR I'm happy to review it :)
