### ISSUE TITLE
ios 12 support

### ISSUE THREAD

**Issue by DavidKababyan** [hyperoslo/ImagePicker#423]
Hey, do you plan to update the pods to support iOS 12 and swift 4.2?

**Comment by wbarlet** [comment]
**UIControlState** was obsolete in Swift 4.2, renamed to **UIControl.State**
**NSLayoutAttribute** was obsolete in Swift 4.2, ranamed to **NSLayoutConstraint.Attribute**
**NSAttributedStringKey** was obsolete in Swift 4.2 renamed to **NSAttributedString.Key**
**UIApplicationOpenSettingsURLString** was obsolete in Swift 4.2, renamed to **UIApplication.OpenSettingsURLString** 
**UIViewAnimationOptions** was obsolete in Swift 4.2 renamed to **UIView.AnimationOptions**
**sendSubView(toBack:)** was obsolete in Swift 4.2 renamed to **sendSubViewToBack(_:)**
**UIDeviceOrientationDidChange** was obsolete in Swift 4.2 renamed to **UIDevice.orientationDidChangeNotification**

**Comment by appsailor** [comment]
@wbarlet @DavidKababyan  I have a forked branch with Swift 4.2 support. I use it for my personal proeject kawntr.com

Here is the Podfile line

    pod 'ImagePicker', :git => 'https://github.com/appsailor/ImagePicker.git', :branch => 'feature/Swift-4.2'

**Comment by karthicknachimuthu** [comment]
> @wbarlet @DavidKababyan I have a forked branch with Swift 4.2 support. I use it for my personal proeject kawntr.com
> 
> Here is the Podfile line
> 
> ```
> pod 'ImagePicker', :git => 'https://github.com/appsailor/ImagePicker.git', :branch => 'feature/Swift-4.2'
> ```

I have tried this. Getting below error in my code. Can you please help?

`'Configuration' initializer is inaccessible due to 'internal' protection level`

>

**Comment by MaxvandeLaar** [comment]
@karthicknachimuthu 

When using the forked branch you can set the configurations as such:

```
        Configuration.doneButtonTitle = "Finish"
        Configuration.noImagesTitle = "Sorry! There are no images here!"
        Configuration.recordLocation = false
        
        let imagePickerController = ImagePickerController()
        imagePickerController.delegate = self
        present(imagePickerController, animated: true, completion: nil)
```

There is no need to initialise the Configuration

**Comment by linkfei** [comment]
@MaxvandeLaar   I tried your branch, but it doesn't support iPhone X

**Comment by linkfei** [comment]
@appsailor I tried your branch, but it doesn't support iPhone X
