### ISSUE TITLE
Is NSLocationWhenInUseUsageDescription required? App rejection.

### ISSUE THREAD

**Issue by makeitTim** [hyperoslo/ImagePicker#424]
Thanks for the library.

The library requests location access? I see the `LocationManager` class does call `requestWhenInUseAuthorization()`, but I can't determine its use?

I had an app initially rejected for requesting location access without a reason. I appealed and got it through but it's not clear what's going on.

**Comment by sbporter** [comment]
you can disable record location in the configuration.
`            imagePickerController.configuration.recordLocation = false
`

**Comment by makeitTim** [comment]
Thanks for the response. Ok, so disabling that means I don't need to request location at all and could exclude it from the plist privacy requests?

If I DID want to keep the location EXIF in an image (I say jpeg compressed and allowed user to post) ... how do I get that? The `doneButtonDidPress()` returns `UIImage`s, but I don't think `UIImage` manages any metadata.
