### ISSUE TITLE
it can not load icloud picture

### ISSUE THREAD

**Issue by yuanjieaili** [hyperoslo/ImagePicker#428]
it can not load icloud picture

**Comment by LSK-01** [comment]
simply press 'icloud'

**Comment by ETGgames** [comment]
finnaly we have a solution ^^ !!! Thanks LS-K!!

**Comment by LSK-01** [comment]
no problem ETGgames!!!11!1! happy to help as always!!!!!1111

**Comment by Movsisyan** [comment]
The same problem. If one of chosen images is a compressed and should load from icloud then none of selected images is added.

So what is the solution?

**Comment by LSK-01** [comment]
simply press 'icloud'

**Comment by EthanSK** [comment]
finnaly we have a solution ^^ !!! Thanks LS-K!!

**Comment by LSK-01** [comment]
no problem ETGgames!!!11!1! happy to help as always!!!!!1111

**Comment by Movsisyaan** [comment]
The same problem. If one of chosen images is a compressed and should load from icloud then none of selected images is added.

So what is the solution?
