### ISSUE TITLE
Do you think imageDidDrop should calls dismissIfNeeded?

### ISSUE THREAD

**Issue by cpromise** [hyperoslo/ImagePicker#432]
When ```imageLimit``` is set to ```1``` and touches the photo already selected, the imagePicker dismisses.

Is that what you expected?

I wonder why just touching the selected photo does not deselect the photo.

**Comment by batuhangobekli** [comment]
+1

**Comment by batuhangobekli** [comment]
@3lvis did you look at it?

**Comment by 3lvis** [comment]
Haven't had the time... sorry!

**Comment by 3lvis** [comment]
Happy if somebody can have a look a this.
