### ISSUE TITLE
IMAGE NSURL 

### ISSUE THREAD

**Issue by Satyendrabhati** [hyperoslo/ImagePicker#452]
How do i get image url or path of url?.In default picker i will get url by following code : 
 let imageUrl = info[UIImagePickerController.InfoKey.referenceURL] as! NSURL
I Need this image url with this picker view.

**Comment by tasleem96** [comment]
I'm facing the same issue but judging by the fact this was closed without any comments I guess that's not going to happen anytime soon, I guess I have to delete this and find another solution

**Comment by 3lvis** [comment]
Hi @tasleem96, this library is discontinued, finding another one sounds like a good idea.
