### ISSUE TITLE
Does it support screen rotation on the iPad?

### ISSUE THREAD

**Issue by chtk3131** [hyperoslo/ImagePicker#455]
Hello.
When I used your Demo App on an iPad, the text would not rotate when rotating the screen.
Is there anything I should set up when considering screen rotation?

swift: 5.1.3
xcode: 11.3.1
target device: iOS12.0 iPhone,iPad
iPad:12.1.1

![IMG_0032](https://user-images.githubusercontent.com/45441215/84990341-f3f36900-b17f-11ea-9210-29b714a5462b.jpg)

**Comment by 3lvis** [comment]
Hi @chtk3131! Demo should be rotating now https://github.com/hyperoslo/ImagePicker/commit/01c7a04b633cdce1192e931e2089088e00ef6fb6

**Comment by TwitchedDesign** [comment]
Hi @3lvis  

issue still present, demo is not rotating either.

**Comment by willm132** [comment]
Using SPM this is still happening for me.

My application works in all device rotations, but when I present the Image Picker, the camera only shows portrait.
