### ISSUE TITLE
Cannot unselecting image when setting "imageLimit" to 1.

### ISSUE THREAD

**Issue by azizimarouan** [hyperoslo/ImagePicker#470]
This issue was opened in #465 and it is closed without being fixed.

**Comment by azizimarouan** [comment]
I deleted this code [link_1](https://github.com/hyperoslo/ImagePicker/blob/ecee6e25559c64ce117aef61ee52dcc529e5ee23/Source/ImagePickerController.swift#L237) and [link_2](https://github.com/hyperoslo/ImagePicker/blob/ecee6e25559c64ce117aef61ee52dcc529e5ee23/Source/ImagePickerController.swift#L282) and the issue is fixed for me! please update it!

**Comment by Tj3n** [comment]
You have to write like this:
```
        let config = Configuration()
        config.allowMultiplePhotoSelection = false
        let imagePicker = ImagePickerController(configuration: config)
        imagePicker.delegate = self
```
not `imagePicker.imageLimit = 1`

**Comment by azizimarouan** [comment]
Thank you @Tj3n , but I think this should be mentioned in the README.md file.

**Comment by 3lvis** [comment]
Added to the README https://github.com/hyperoslo/ImagePicker/commit/4cfb7e30660960f63120cd3fbbc62c14fb193d8a
