### ISSUE TITLE
Configuration Class conflict to UIButton.Configuration

### ISSUE THREAD

**Issue by EagleKang** [hyperoslo/ImagePicker#493]
see the picture below. what can I do ?
![WechatIMG35603](https://github.com/user-attachments/assets/e60c8581-7824-4e6f-a104-5177addbf968)

**Comment by EagleKang** [comment]
codes not updated. 
<img width="1178" alt="image" src="https://github.com/user-attachments/assets/145a5526-be0f-4113-b942-4cc4d4092f01">

**Comment by 3lvis** [comment]
https://github.com/hyperoslo/ImagePicker/releases/tag/3.3.0
