### ISSUE TITLE
How to limit number of images to select?  

### ISSUE THREAD

**Issue by thrilller** [hyperoslo/ImagePicker#66]
There can be scenario when only one image is to be selected from picker e.g user profile image change.  Tapping on different image will deselect previous one in gallery.

**Comment by zenangst** [comment]
We don't support this feature at the moment but it would be a nifty enhancement. :sunglasses:

**Comment by RamonGilabert** [comment]
We are planning to do a major release by the start of next year, after holidays! :) So we could add that :dancer:

**Comment by RamonGilabert** [comment]
As #68 implements, using the branch `development` you are going to be able to, when you create the ImagePicker, use:

```
let imagePickerController = ImagePickerController()
imagePickerController.imageLimit = 5
```
