### ISSUE TITLE
Update for iOS 9.0

### ISSUE THREAD

**Issue by AnotherCoolDude** [hyperoslo/ImagePicker#67]
Library has not been updated for iOS 9.0. There are no errors, but a bunch of warnings :)

**Comment by zenangst** [comment]
Hey @AnotherCoolDude, could you post some of the warnings that you are getting so that we can investigate the issues? :sunglasses:

**Comment by sairamkotha** [comment]
Hi your using "writeImageToSavedPhotosAlbum" this function deprecated in  ios 9.0 need to use "creationRequestForAssetFromImage" in case of IOS 9.0. This function is available in ios 8.1

**Comment by sairamkotha** [comment]
Update repository and remove deprecated functions like this. Use photos framework in case of ALasset Library

**Comment by zenangst** [comment]
@sairamkotha, thanks for the additional info, we will have a look 😎

**Comment by RamonGilabert** [comment]
Implemented in #68. You are going to have to use the branch `development` to have no warnings. Also deleted the warnings in the Demo. :)
