### ISSUE TITLE
Status bar is not reset when ImagePicker is removed

### ISSUE THREAD

**Issue by olivierlesnicki** [hyperoslo/ImagePicker#69]
The status bar is hidden when the ImagePicker is opened but doesn't re-appear once the ImagePicker is closed.

**Comment by zenangst** [comment]
@olivierlesnicki thanks for bringing this to our attention, we will investigate! 🔍

**Comment by richardoti** [comment]
@olivierlesnicki That's a tricky question. StatusBar should be hidden when picker is opened and should restore to its previous state after it has been dismissed.

Although, it is possible to restore StatusBar state after dismissal, I think, it's better approach to reset it manually to the desired state.

It's just a single line:
`[[UIApplication sharedApplication] setStatusBarHidden:NO withAnimation:UIStatusBarAnimationFade];`
There might be some corner use-cases when another screen is being shown after dismissal, so Picker should care only about own StatusBar state.

**Comment by olivierlesnicki** [comment]
I know it's simple to achieve manually!

However, if another screen is being shown after dismissal it means it would have been triggered manually by the app. In this case the app will need to hide the status bar accordingly.

I think modals should always clean up after themselves - or not touch the status bar at all. And leave the decision to the app to show/hide it (with an opt-in) maybe.

**Comment by RamonGilabert** [comment]
Fixed in #71. This will take the current status bar hidden status and put it again before dismissal.

**Comment by olivierlesnicki** [comment]
Good job!

**Comment by RamonGilabert** [comment]
@richardoti, following you a bit up here, even if it's up to you to choose the state of the picker, I think the Picker shouldn't vary the state of the Status Bar, so if it's hidden in the first place, ImagePicker should be presented, dismissed, and not touch the Status Bar opacity at all. If it's not hidden, the same thing.

**Comment by richardoti** [comment]
@RamonGilabert yeah, that's a good solution too, it's not black-or-white question. Restoring status bar to the previous state will suite 90+% of users. Those who want custom behavior already know how to implement it.
