### ISSUE TITLE
Reset images selected without destroying the ImagePicker ViewController

### ISSUE THREAD

**Issue by olivierlesnicki** [hyperoslo/ImagePicker#70]
I want to keep a reference to the imagePicker ViewController in memory for quick show/hide. How can I reset the assets selected once the ImagePicker is hidden (without destroying it)

**Comment by RamonGilabert** [comment]
You access the selected stack and remove all the images. Although ImagePicker is intended to keep reference for a while, in a composer for example, when you are building a post, and not be used as a general thing that you keep reference to. You can though.

```swift
let imagePickerController = ImagePickerController()
imagePickerController.stack.assets = []
```

**Comment by olivierlesnicki** [comment]
@RamonGilabert thanks! :)

**Comment by olivierlesnicki** [comment]
Simply calling `imagePickerController.stack.assets = []` doesn't refresh the existing UI elements (the old images are still showing as selected, the count still shows as 1)

**Comment by richardoti** [comment]
@olivierlesnicki just resetting assets won't work.
There is a method intended for that purpose:
```Swift
 public func resetAssets(assetsArray: [PHAsset])
```

so, just try:
```Swift
picker.stack.resetAssets([PHAsset]())
```

This design is related to some lower-level issues with property observers and notifications. Using the function I've provided the notification will be posted and all UI components should update their state automatically.

**Comment by zenangst** [comment]
@olivierlesnicki did @richardoti's suggestion work for you?

**Comment by olivierlesnicki** [comment]
@zenangst haven't tried yet

**Comment by aashishdhawan** [comment]
This has been taken care of in #162.
