### ISSUE TITLE
Rotation can mess up the image gallery sizes

### ISSUE THREAD

**Issue by olivierlesnicki** [hyperoslo/ImagePicker#73]
My project is set to display in `Portrait` mode only. When I rotate the device in landscape mode and open the ImagePicker, the images in the image gallery are showing in an altered ratio yet all the layout elements are correctly showing in portrait.

**Comment by RamonGilabert** [comment]
Hey @olivierlesnicki! I won't be able to check that until I have a phone to do it actually. I want to test on device.

The idea was just to show ImagePicker in Portrait, we could use the same layout in Landscape only rotating the images, but not sure about that.

**Comment by BenchR267** [comment]
@olivierlesnicki Please check the branch in my fork at https://github.com/hyperoslo/ImagePicker/pull/104 if the issue still appears. I fixed some problems regarding the ortientation.

**Comment by zenangst** [comment]
@olivierlesnicki could you please check `master` now to see if this case is fixed.

**Comment by zenangst** [comment]
Closing this one, we think it might be fixed in `1.3.0`, feel free to re-open if it is still an issue.
