### ISSUE TITLE
StatusBar is kept hidden when leaving view

### ISSUE THREAD

**Issue by sohayb** [hyperoslo/ImagePicker#78]
I'm working on the ````development```` branch and you're setting this in ````viewWillAppear````:
````UIApplication.sharedApplication().statusBarHidden = true```` and not setting it back to the way it was in ````viewWillDisappear```` whilst on the main branch it's working great. Working on the ````development```` branch to get to set the images limit

**Comment by olivierlesnicki** [comment]
See https://github.com/hyperoslo/ImagePicker/issues/77

**Comment by RamonGilabert** [comment]
Hey @sohayb this is that you should point to master! I'll do a release today with the branch development and you are going to be able to use it through CocoaPods.

**Comment by sohayb** [comment]
thanks @RamonGilabert !

**Comment by RamonGilabert** [comment]
Made a release @sohayb, keep me posted on the result.

Closing for now! :)

**Comment by sohayb** [comment]
it worked man! thank you :+1:
