### ISSUE TITLE
Not able to force only 1 picture selection

### ISSUE THREAD

**Issue by iballan** [hyperoslo/ImagePicker#81]
I am not able to choose only one picture.

**Comment by zenangst** [comment]
Hey @iballan, have you tried the `development` branch?

This PR was merged a while ago - https://github.com/hyperoslo/ImagePicker/pull/68.

Hope that helps, cheers!

**Comment by iballan** [comment]
@zenangst exactly what i was asking for. thank you so much

**Comment by zenangst** [comment]
@iballan cheers and a happy new year to you buddy :rocket:

**Comment by iballan** [comment]
happy new year @zenangst , i wish you all the best. I would like to add that doing such a great library and keeping it open source, in order to help us (new and less experienced developers) to do great apps with your tools, motivates us to do the same and help others in the coming year.

Thank you and everybody that supports open source.
