### ISSUE TITLE
Can't run demo app as-is

### ISSUE THREAD

**Issue by jeffhatz** [hyperoslo/ImagePicker#98]
There are errors in the project related to CocoaPods, so the demo app can't run as-is from the ZIP download of the library.
![screen shot 2016-01-21 at 8 52 59 pm](https://cloud.githubusercontent.com/assets/1778967/12501986/02fe367c-c081-11e5-9b86-211fd6029608.png)

**Comment by Ross-Gibson** [comment]
To resolve, follow these steps:

1. Open a new Terminal window, and run: ```sudo gem install cocoapods```
2. Open another new Terminal window, and from the directory of the unzipped project navigate to the directory of the demo project. Like this ``` cd ImagePicker-master/Demo/ImagePickerDemo```
3. From this directory, run: ```pod install```
4. Open the workspace, ImagePickerDemo.xcworkspace

**Comment by zenangst** [comment]
Hey @jeffhatz, like @Ross-Gibson said. You need to run `pod install` for the demo as the `Pods/` folder is ignored by git. Hope his suggestion got you up and running with the demo. Gonna close this :sunglasses: 

@Ross-Gibson thanks for helping out with responding to issues, you get :cake:
